### ISSUE TITLE
Headless mode not working on linux distributions.

### ISSUE THREAD

**Issue by AdonisCodes** [kaliiiiiiiiii/Selenium-Driverless#101]
I run my script, no errors, but it stays stuck at the 

![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/122154257/54d4c8c2-2ba6-48ef-b78c-8ea605316ca2)

It never gets to the "working" part.

But it does have a pid for chromium:
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/122154257/e5af6ceb-e053-4412-9531-2e0fdc342364)

I am not smart in this kind of systems dev stuff. I just build using tools like selenium-driverless.
Thanks!

**Comment by kaliiiiiiiiii** [comment]
Try `webdriber.Chrome(debug=True)`
Most likely an issue with Chromium or your distro & not my library, closing therefore for now.
Feel free to update me tho:)
