### ISSUE TITLE
save --user-data-dir

### ISSUE THREAD

**Issue by miltonvo** [kaliiiiiiiiii/Selenium-Driverless#103]
its possible to save user data dir for reuse on next launch of instance?

i got it using :
options.add_argument(f"--user-data-dir={absolute_path}")

but when i close the instance the dir is removed

**Comment by kaliiiiiiiiii** [comment]
> i got this when try to execute:
> 
> Chrome.quit() got an unexpected keyword argument 'clean_dirs'
> 
> without argument its works close correctly but remove user data folder too

make sure to update your version. 
`pip install --upgrade selenium-driverless`
