### ISSUE TITLE
[Feature Request] Stealth scrolling

### ISSUE THREAD

**Issue by Vadhvis** [kaliiiiiiiiii/Selenium-Driverless#120]
Some websites require scrolling to fully load the data (ie: Bet365 is an example). However, said websites often have overflow in inner divs that require selection through js to be able to scroll them breaking any stealth measures of this library.

Would it be possible to add internal functions to scroll selected elements through selenium?

**Comment by kaliiiiiiiiii** [comment]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/c207798337d07e6fd98dc44e86ed5b59f3c67f48/src/selenium_driverless/types/webelement.py#L612-L621

**Comment by Vadhvis** [comment]
Not sure how I missed that, thanks a lot!

**Comment by kaliiiiiiiiii** [comment]
> Not sure how I missed that, thanks a lot!

no worries:)
Isn't documented at all:)
