### ISSUE TITLE
remove license nag message

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/Selenium-Driverless#122]
- no one cares about licenses, especially not some closed-source commercial service
- the `site-packages/selenium_driverless/` folder should be treated as read-only, because `OSError: [Errno 30] Read-only file system: '/nix/store/7zwbwl78sn5ma5lxzfacz7mm065k0f16-selenium-driverless-unstable-2023-10-29/lib/python3.10/site-packages/selenium_driverless/files/is_first_run'`

https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/c207798337d07e6fd98dc44e86ed5b59f3c67f48/src/selenium_driverless/webdriver.py#L85-L91

**Comment by kaliiiiiiiiii** [comment]
> * no one cares about licenses, especially not some closed-source commercial service

How's that a reason to remove that message? 

Do you include yourself as well with `no one cares` ?

**Comment by milahu** [comment]
> How's that a reason to remove that message?

generally, these license games are stupid, they only annoy small users
the "big guys" you wanna annoy dont care one second

also, all the cc licenses are painfully verbose

patents/copyright are a problem, not a solution

> Do you include yourself as well with `no one cares` ?

yep. i will use your tool anyway, simply because its better than a [patched binary chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver)
and because i need [cdp](https://github.com/kaliiiiiiiiii/CDP-Socket) to get the raw traffic, so im happy with your tools : )

if i had too much time (haha) i would rewrite it with a MIT license, but well

**Comment by kaliiiiiiiiii** [comment]
> > How's that a reason to remove that message?
> 
> generally, these license games are stupid, they only annoy small users the "big guys" you wanna annoy dont care one second
> 
> also, all the cc licenses are painfully verbose
> 
> patents/copyright are a problem, not a solution

I'd consider that mostly a matter of opinion. Ofc some just don't care. \
Still pretty sure bigger companies care or at least would be liable

> > Do you include yourself as well with `no one cares` ?
> 
> yep. i will use your tool anyway, simply because its better than a [patched binary chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) and because i need [cdp](https://github.com/kaliiiiiiiiii/CDP-Socket) to get the raw traffic, so im happy with your tools : )
>
> if i had too much time (haha) i would rewrite it with a MIT license, but well

Well unfortunately, I generally reject requests from people violating//ignoring the licence unless it's about a bug.
So yeah - message won't get removed. I will fix that read-only path tho:)

**Comment by milahu** [comment]
this is "nagging" because by using your software, people automatically accept your license
so there is no need to remind users...

also, `print(LICENSE, file=sys.stderr)` is no dialog, where the user actively has to "accept license"


```py
async def is_first_run():
    path = DATA_DIR + "/is_first_run"
    if os.path.isfile(path):
        res = await read(path, sel_root=False)
        if res == __version__:
            return False
        else:
            await write(path, __version__, sel_root=False)
            print(LICENSE, file=sys.stderr)
            # new version
            return None
    else:
        # first run
        print(LICENSE, file=sys.stderr)
        await write(path, __version__, sel_root=False)
        return True
```

similar situation with "gnu parallel"
https://github.com/NixOS/nixpkgs/issues/110584#issuecomment-766158970
debian/arch/suse linux have removed the nagging "will cite" message
because why not, you cannot prevent users from patching your software

**Comment by kaliiiiiiiiii** [comment]
> this is "nagging" because by using your software, people automatically accept your license so there is no need to remind users...

In my experience - some people don't even look at the licence. That's why I've added the message.

> also, `print(LICENSE, file=sys.stderr)` is no dialog, where the user actively has to "accept license"

It's not my goal to require user-interaction👀


> `src/selenium_driverless/utils/utils.py`
> 
> ```python
> async def is_first_run():
>     path = DATA_DIR + "/is_first_run"
>     if os.path.isfile(path):
>         res = await read(path, sel_root=False)
>         if res == __version__:
>             return False
>         else:
>             await write(path, __version__, sel_root=False)
>             print(LICENSE, file=sys.stderr)
>             # new version
>             return None
>     else:
>         # first run
>         print(LICENSE, file=sys.stderr)
>         await write(path, __version__, sel_root=False)
>         return True
> ```
> 
> similar situation with "gnu parallel" [NixOS/nixpkgs#110584 (comment)](https://github.com/NixOS/nixpkgs/issues/110584#issuecomment-766158970) https://news.ycombinator.com/item?id=15319715 debian/arch/suse linux have removed the nagging "will cite" message because why not, you cannot prevent users from patching your software

Well again, the message with mine doesn't require any user-interaction. On a technical level, I do not see any issue why my message would break anything?

**Comment by milahu** [comment]
> On a technical level, I do not see any issue why my message would break anything?

the technical problem is storing runtime state in `site-packages/`
runtime state belongs to `$HOME/.cache/selenium_driverless/yeah-i-know-your-license`
and maybe accept an env like `SELENIUM_DRIVERLESS_YEAH_I_KNOW_YOUR_LICENSE`

alternative:
always show the message with a custom logger name like 

```py
logging.getLogger("selenium_driverless.license_nagger").info("please read my license: ...")
```

so i can disable the message with

```py
logging.getLogger("selenium_driverless.license_nagger").setLevel(logging.WARNING)
```

> In my experience - some people don't even look at the licence.

makes no difference. when people use it, they accept the license
especially, when people run some commercial operation, they must check licenses
so currently, the nag message is only hurting normal users

**Comment by kaliiiiiiiiii** [comment]
> > On a technical level, I do not see any issue why my message would break anything?
> 
> the technical problem is storing runtime state in `site-packages/` 

Uh don't think that's the case anymore. See https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/4b71a5ab59a193d41eab80ed8f68a66e8ad5c230/src/selenium_driverless/utils/utils.py#L20 and https://github.com/ActiveState/appdirs?tab=readme-ov-file#some-example-output

> alternative: always show the message with a custom logger name like
> 
> ```python
> logging.getLogger("selenium_driverless.license_nagger").info("please read my license: ...")
> ```
> 
> so i can disable the message with
> 
> ```python
> logging.getLogger("selenium_driverless.license_nagger").setLevel(logging.WARNING)
> ```

well my goal isn't to make it that easy to disable the message:)

**Comment by milahu** [comment]
> `DATA_DIR = user_data_dir(...`

ok, so disabling the message is as simple as

```py
# not tested...

import selenium_driverless
import selenium_driverless.utils.utils
import os

async def selenium_driverless_disable_license_nagger():
    __version__ = selenium_driverless.__version__
    DATA_DIR = selenium_driverless.utils.utils.DATA_DIR
    read = selenium_driverless.utils.utils.read
    write = selenium_driverless.utils.utils.write
    path = DATA_DIR + "/is_first_run"
    if os.path.isfile(path):
        res = await read(path, sel_root=False)
        if res == __version__:
            return
        await write(path, __version__, sel_root=False)
        return
    await write(path, __version__, sel_root=False)

async def main():
    await selenium_driverless_disable_license_nagger()
    # ...
```

this nagging just makes no sense with open-source software
because users can always [patch your code to remove the nagger](https://github.com/milahu/nur-packages/blob/3b4a5e5a2f2cd5ad886aac2f038b6701836608ab/pkgs/python3/pkgs/selenium-driverless/selenium-driverless.nix#L41)

**Comment by kaliiiiiiiiii** [comment]
> > `DATA_DIR = user_data_dir(...`
> 
> ok, so disabling the message is as simple as

Censored that code btw:)

> this nagging just makes no sense with open-source software because users can always [patch your code to remove the nagger](https://github.com/milahu/nur-packages/blob/3b4a5e5a2f2cd5ad886aac2f038b6701836608ab/pkgs/python3/pkgs/selenium-driverless/selenium-driverless.nix#L41)
> 
> (with closed-source software i can patch the binary...)

Well of course there are ways - and I won't obfuscate any stuff to prevent that. Obfuscated stuff within packages is in my opinion just scetchy👀

**Comment by milahu** [comment]
> Censored that code for future readers btw:)

wtf?

do you think that your users are too stupid to write 10 lines of python
to create some stupid file in `$HOME/.config/`?

> I won't obfuscate any stuff

you just censored my comment

**Comment by kaliiiiiiiiii** [comment]
> > Censored that code for future readers btw:)
> 
> wtf?
> 
> do you think that your users are too stupid to write 10 lines of python to create some stupid file in `$HOME/.config/`?

no haha.. Easy stuff indeed
> 
> > I won't obfuscate any stuff
> 
> you just censored my comment

Indeed, I don't really like when people share ways to remove the message. censoring!=obfuscation tho

> your "anti capitalist" fight is just ridiculous

I don't think there's the need to fight in here tho:) Let's keep.

**Comment by milahu** [comment]
meanwhile, in a parallel universe... https://github.com/milahu/selenium_driverless/commit/bd40f95c90809aab49c7db457cc4c59424f58806
