### ISSUE TITLE
How to get ReadyState without execute_script?

### ISSUE THREAD

**Issue by xrkk** [kaliiiiiiiiii/Selenium-Driverless#130]
For now, can get ReadyState using `execute_script('return document.readyState;')`, but it may got caught. How to get ReadyState without execute_script?

**Comment by kaliiiiiiiiii** [comment]
> For now, can get ReadyState using `execute_script('return document.readyState;')`, but it may got caught. How to get ReadyState without execute_script?

@xrkk Please do not open any issue unless it's a bug.
What exactly do you mean by "getting caught" ?

**Comment by xrkk** [comment]
> @xrkk Please do not open any issue unless it's a bug.

Sorry about this.



> What exactly do you mean by "getting caught" ?

As what you said `Jep, JavaScript is detectable this way tho.`, here: https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/127#issuecomment-1846740827

**Comment by kaliiiiiiiiii** [comment]
soo did you try using https://github.com/kaliiiiiiiiii/Selenium-Driverless#unique-execution-contexts ?
