### ISSUE TITLE
driver.get throws TimeoutError on file downloads

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/Selenium-Driverless#140]
when i open some url with `driver.get(url)`
and the server returns a file download
([Content-Disposition: attachment](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition))
then `driver.get` hangs and throws a `TimeoutError`

as a workaround, im checking the `~/Downloads` folder
and wait until the file was written

the response can be either a file download, or an html error page, so `driver.get(url, wait_load=False)` would be wrong

CDP has the experimental [Browser.downloadWillBegin](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#event-downloadWillBegin)

> Fired when page is about to start a download.

but `download_will_begin` is never called

```py
    # never called?
    def download_will_begin(*a, **k):
        print(f"download_will_begin: a={a} k={k}")

    await driver.add_cdp_listener("Browser.downloadWillBegin", download_will_begin)
    # wait for add_cdp_listener?!
    await asyncio.sleep(3)

    await driver.get(url, referrer=referrer, wait_load=False)
    await asyncio.sleep(99999999)

    await driver.remove_cdp_listener("Browser.downloadWillBegin", download_will_begin)
```

another possible solution: use a different downloads folder for each download

```py
    await driver.get("chrome://settings/downloads")
    # click on #changeDownloadsPath
    # enter new downloads folder
    # click OK
    await driver.get(url, wait_load=False)
    # wait for the file to be created in the downloads folder
    # or check driver.page_source for html error page
```

another possible solution: run chromium in verbose mode and parse stdout log messages

another possible solution: monitor the `chrome://downloads/` page
which has source urls and destination filepaths
the page is based on `chrome://downloads/downloads.js`
see also [How best to test file download links using Selenium](https://sqa.stackexchange.com/a/27342/57619)
see also [Selenium Webdriver with Shadow DOM](https://stackoverflow.com/questions/51346883/selenium-webdriver-with-shadow-dom)

**Comment by kaliiiiiiiiii** [comment]
> but download_will_begin is never called
thanks for testing

> ```python
> await driver.get("chrome://settings/downloads")
> # click on #changeDownloadsPath
> # enter new downloads folder
> # click OK
>```

No need fo hackish stuff - there's `Browser.setDownloadBehavior` to set the path. Would however prefer a static download path.

> another possible solution: run chromium in verbose mode and parse stdout log messages

That causes issues as `subprocess.PIPE` can make chrome hang when getting a lot of messages. see https://github.com/electron/electron/issues/35399#issuecomment-1751523513
And yeah - ofc we'd run a tread to processs the pipe stdout. However, I'm not sure about timing etc. as well.

> chrome://downloads/

uh yeah, likely would even work with passing JS events. However, I'm not sure if that's gonna work with contexts (incognito) and ofc, we preferably don't want a open tab all the time.

#### My conclusion
all of those approaches seem a bit "hackish" to me. More convincing to me are here passive request events as discussed at https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/148#issuecomment-1889808446 as well.

Also:
Possibly, the 20s timeout at https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/24a3513305f833fac600ec8e31bcd5e9df955162/src/selenium_driverless/types/target.py#L228 should not be hardcoded. (assumption: CMD returns when network request is done, relevant for large file downloads)

**Comment by kaliiiiiiiiii** [comment]
> 1. we must enable download events with [Browser.setDownloadBehavior](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-setDownloadBehavior)

Ah yep that's good to know, thanks.

> so this is not too complex, but requires setting up some event listeners
> which could interfere with listeners added by the user
> so maybe this is out of scope for Selenium-Driverless

Actually, here I thought about having 2 sockets for each target. One for users and one for internals.
This won't resolve all interfaces (such as network interception), however, event subscriptions are isolated to me knowledge.

**Comment by milahu** [comment]
i suggest to close this as "wontfix"

i assume that the original `selenium` has the same limitation
and `selenium_driverless` should be a drop-in replacement for `selenium` (plus `async`)

and this is too complex to solve in `selenium`
instead, consumers should wrap the `driver.get` call
parse response headers, handle streams, handle CDP events, etc
(this is why i started [aiohttp_chromium](https://github.com/milahu/aiohttp_chromium))

**Comment by kaliiiiiiiiii** [comment]
This one's gonna be fixed by https://github.com/kaliiiiiiiiii/Selenium-Driverless/commit/51028b42dba02c9aec7b2b3d91a813556f0f2212#diff-6ddf02e9f090683f5175795f0bba0dcc9bc08e4e663bd0c3ab594eefc79b86eaR214-R252

**Comment by kaliiiiiiiiii** [comment]
> This one's gonna be fixed by [51028b4#diff-6ddf02e9f090683f5175795f0bba0dcc9bc08e4e663bd0c3ab594eefc79b86eaR214-R252](https://github.com/kaliiiiiiiiii/Selenium-Driverless/commit/51028b42dba02c9aec7b2b3d91a813556f0f2212#diff-6ddf02e9f090683f5175795f0bba0dcc9bc08e4e663bd0c3ab594eefc79b86eaR214-R252)

resloved now.
https://kaliiiiiiiiii.github.io/Selenium-Driverless/classes/ChromeOptions/#selenium_driverless.types.options.Options.downloads_dir

**Comment by milahu** [comment]
related:

before calling `Network.getResponseBody`
we should wait for the `Network.loadingFinished` event
otherwise `Network.getResponseBody` can return
only the first 65536 bytes (64KiB) of the response

see also
https://github.com/ChromeDevTools/devtools-protocol/issues/44
https://github.com/milahu/aiohttp_chromium/commit/0fbd29cb5d123470e005203a59e23c39cc24eb85

this is the problem with CDP events:
the user may want to handle CDP events
and then handling these events in selenium_driverless is "too much"

the user will want to handle both events:
`Network.loadingFinished` for inline content
`Browser.downloadWillBegin` for file downloads

...or do you want to handle both events in selenium_driverless?

**Comment by kaliiiiiiiiii** [comment]
> related:
> 
> before calling `Network.getResponseBody` we should wait for the `Network.loadingFinished` event otherwise `Network.getResponseBody` can return only the first 65536 bytes (64KiB) of the response
> 
> see also [ChromeDevTools/devtools-protocol#44](https://github.com/ChromeDevTools/devtools-protocol/issues/44) [milahu/aiohttp_chromium@0fbd29c](https://github.com/milahu/aiohttp_chromium/commit/0fbd29cb5d123470e005203a59e23c39cc24eb85)
> 
> this is the problem with CDP events: the user may want to handle CDP events and then handling these events in selenium_driverless is "too much"

=> multiple WS connections to a target considerable.
> 
> the user will want to handle both events: `Network.loadingFinished` for inline content `Browser.downloadWillBegin` for file downloads
> 
> ...or do you want to handle both events in selenium_driverless?

hm doesn't `Page.navigate` return after the full response has been received? At least for big file downloads, I noticed that it takes longer

**Comment by milahu** [comment]
> doesn't `Page.navigate` return after the full response has been received?

aah, probably yes

i observed the "65536 bytes issue" when fetching assets (child requests)
