### ISSUE TITLE
Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)" License.

### ISSUE THREAD

**Issue by dxdate** [kaliiiiiiiiii/Selenium-Driverless#143]
When I run my code, I get this error, although I do not use the code for business solutions, etc.:

This package has a "Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)" License.
Therefore, you'll have to ask the developer first if you want to use this package for your business.
https://github.com/kaliiiiiiiiii/Selenium-Driverless

how do I remove this warning?

**Comment by kaliiiiiiiiii** [comment]
It will only be shown on the first run of a specific Version.
Providing a ways to remove it would contradict the concept uf putting it event on there:)
Therefore, I'm closing this issue.
