### ISSUE TITLE
How to create click_and_hold like ActionAchain ?

### ISSUE THREAD

**Issue by quocviet0304** [kaliiiiiiiiii/Selenium-Driverless#146]
Help me with solution pls ?

**Comment by kaliiiiiiiiii** [comment]
https://github.com/kaliiiiiiiiii/Selenium-Driverless?tab=readme-ov-file#pointer-interaction

**Comment by quocviet0304** [comment]
but i only see up, down, and move_to

**Comment by quocviet0304** [comment]
Thanks a lot
