### ISSUE TITLE
sendkeys-elemwrite ? 

### ISSUE THREAD

**Issue by yemrekula0748** [kaliiiiiiiiii/Selenium-Driverless#150]
File "C:\Users\Administrator\Desktop\Proxy-Changer-main\drivertest.py", line 83, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\Proxy-Changer-main\drivertest.py", line 78, in main
    epostagiris.write("yunus")
    ^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'write'
sys:1: RuntimeWarning: coroutine 'Chrome.find_element' was never awaited

async def main():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        await driver.get('---')
        #await driver.sleep(1.5)
        #await driver.wait_for_cdp("Page.domContentEventFired", timeout=10)
        
        # wait 10s for elem to exist
      
      
      
        birincitik = await driver.find_element(By.XPATH, '//*[@id="SupportFormRow.486349168100130"]/div[3]/label[2]')
        await birincitik.click(move_to=True)
        time.sleep(10)

        ikincitik = await driver.find_element(By.XPATH, '//*[@id="SupportFormRow.334536476675719"]/div[4]/label[1]/span')
        await ikincitik.click(move_to=True)
        
        ucuncutik = await driver.find_element(By.XPATH, '//*[@id="SupportFormRow.650238494993366"]/div[4]/label[1]/span')
        await ucuncutik.click(move_to=True)
        
        epostatik = await driver.find_element(By.XPATH, '//*[@id="454337367989067"]')
        await ucuncutik.click(move_to=True)
               
        

        epostagiris = driver.find_element(By.XPATH, '//*[@id="454337367989067"]')
        epostagiris.write("yunus")
        time.sleep(10)
        #await epostagiris.click(move_to=True)

asyncio.run(main())

**Comment by kaliiiiiiiiii** [comment]
You forgot an `await` statement
