### ISSUE TITLE
[feature Reuqest] file upload

### ISSUE THREAD

**Issue by User-Clb** [kaliiiiiiiiii/Selenium-Driverless#152]
upload_but.write(f.read()) ？ It doesn't seem like it works like that

**Comment by User-Clb** [comment]
@kaliiiiiiiiii

**Comment by kaliiiiiiiiii** [comment]
[`DOM.setFileInputFiles`](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-setFileInputFiles) will be used for this

**Comment by User-Clb** [comment]
> [`DOM.setFileInputFiles`](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-setFileInputFiles) will be used for this

file_path = "./test.mp4"
driver.execute_cdp_cmd('DOM.setFileInputFiles', {
    'files': [file_path],
    'nodeId': upload_but.node_id,
    'backendNodeId': upload_but._backend_node_id,
    })  crashes the page
