### ISSUE TITLE
Unable to run on ubnutu 22.04 server

### ISSUE THREAD

**Issue by C0dins** [kaliiiiiiiiii/Selenium-Driverless#155]
I made a flask api which includes the selenium-driverless package to scrape some data and it works flawlessly on my windows 11 machine but will not work on my ubuntu 22.04 server im not even sure if it supports server versions of ubnutu

**Comment by kaliiiiiiiiii** [comment]
Maybe you're just getting detected due to tht fingerprint.
Please specify "not work"

**Comment by C0dins** [comment]
i opened a different issue with the code and where it errors

**Comment by C0dins** [comment]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/156
