### ISSUE TITLE
[TODO] serve docs

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/Selenium-Driverless#160]
github pages seems to be active
but i dont see the result at
[kaliiiiiiiiii.github.io/Selenium-Driverless](https://kaliiiiiiiiii.github.io/Selenium-Driverless/)
where is it...?

the link should be in the "about" section of
[github.com/kaliiiiiiiiii/Selenium-Driverless](https://github.com/kaliiiiiiiiii/Selenium-Driverless)

also, currently, the github pages action runs jekyll
but [docs/](https://github.com/kaliiiiiiiiii/Selenium-Driverless/tree/master/docs) looks like static html files, generated by [sphinx](https://www.sphinx-doc.org/en/master/)

[pypi.org/project/selenium-driverless](https://pypi.org/project/selenium-driverless/)
has the same url for homepage, docs, source

**Comment by milahu** [comment]
> I at first tried to serve the spinx stuff over github pages

https://duckduckgo.com/?q=sphinx+docs+%22github+pages%22 ...?

> all path at `_static/*` didn't resolve correctly

a common issue with SSG and github pages are absolute links
which drop the root path `/Selenium-Driverless`

**Comment by kaliiiiiiiiii** [comment]
> > I at first tried to serve the spinx stuff over github pages
> 
> https://duckduckgo.com/?q=sphinx+docs+%22github+pages%22 ...?
haha fair enough, by bad😂

https://stackoverflow.com/questions/62626125/github-pages-with-sphinx-generated-documentation-not-displaying-html-correctly
> 
> > all path at `_static/*` didn't resolve correctly
> 
> a common issue with SSG and github pages are absolute links which drop the root path `/Selenium-Driverless`

**Comment by kaliiiiiiiiii** [comment]
Resolved by https://github.com/kaliiiiiiiiii/Selenium-Driverless/commit/36c7e05452317f31e4051356e489875216b011a1

See https://kaliiiiiiiiii.github.io/Selenium-Driverless/

Note: Documentation isn't complete yet at all:)
