### ISSUE TITLE
[BUG] `By.CSS_SELECTOR` wrong number of elements

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/Selenium-Driverless#162]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/5f56548a3c2bade6d42edda7bcc8085fcf8afff0/src/selenium_driverless/types/deserialize.py#L560-L566

in the `class_name == 'NodeList'` case
`description == "NodeList(15)"`
so `description[-2] == 5`
so `driver.find_elements` only returns 5 of 15 elements

in the `_type == 'htmlcollection'` case
`description == "HTMLCollection(15)"`
...

fix

```diff
-  int(description[-2])
+  int(description[len(class_name)+1:-1])
```

similar #149

**Comment by kaliiiiiiiiii** [comment]
Uhh you're right! Thanks a lot

**Comment by kaliiiiiiiiii** [comment]
I've as well considered using javascript for performance instead. However, returning a list then might not return some details at `depth=1`=>element.

**Comment by milahu** [comment]
hmm? a quickfix would be `Array.from(x.querySelector(y))`

**Comment by kaliiiiiiiiii** [comment]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/commit/0ae3a9655eed5248cc8273cb5b8596cfd3d7377f#diff-af5cc8da593dfc414f4e600521af3a40b1d04d82b4a2c6d6ce147a1f3395213bL563-R567

let's hope I didn't mess up the indexing haha
