### ISSUE TITLE
add support for: css /deep/ combinator == css >>> combinator

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/Selenium-Driverless#163]
the css `/deep/` combinator is useful
to reduce boilerplate code when dealing with shadow DOM

the `/deep/` combinator is no longer supported by `document.querySelector`

> `DOMException: Failed to execute 'querySelector' on 'Document': '... /deep/ ...' is not a valid selector.`

implementing this would require

- parse the CSS selector
  - [cssselect](https://github.com/scrapy/cssselect) for CSS3
  - [cssselect2](https://github.com/Kozea/cssselect2) for CSS4
- split the selector at `/deep/` combinators (or `>>>` combinators)
- for every sub-selector call `document.querySelector` or `parentElement.querySelector`
- on error retry the full chain of sub-selectors to fix `StaleElementReferenceException`

see also

- https://stackoverflow.com/questions/55761810/how-to-automate-shadow-dom-elements-using-selenium
- https://stackoverflow.com/questions/25609678/what-do-deep-and-shadow-mean-in-a-css-selector
- https://stackoverflow.com/questions/51346883/selenium-webdriver-with-shadow-dom

similar #144

**Comment by kaliiiiiiiiii** [comment]
Also, I suppose adding an awaitable property `shaddow` to `WebElement` is worth a consideration

**Comment by milahu** [comment]
> Why not just ust JavaScript at that point?

yeah, less back-and-forth between py and js

`await elem.shadow`?
as a generic interface for `iframe.content_document` and others?

**Comment by kaliiiiiiiiii** [comment]
> > Why not just JavaScript at that point?
> 
> yeah, less back-and-forth between py and js

let's close that issue then:) 

> `await elem.shadow`? as a generic interface for `iframe.content_document` and others?

Exactly. Especially for closed shaddow dom, where JS doesn't have access to me knowledge. 
Shall we open a feature request issue for that?

**Comment by milahu** [comment]
> let's close that issue then

no, this would be a nice feature

this only breaks because chromium removed it
using more javascript is just an implementation detail

```py
div = await driver.find_element(By.CSS_SELECTOR, "iframe /deep/ div")
```

> `await elem.shadow`

for my taste, this should be even simpler

```diff
-  (await iframe.shadow).find_element
+  iframe.find_element
```

```py
iframe = await driver.find_element(By.CSS_SELECTOR, "iframe")
div = await iframe.find_element(By.CSS_SELECTOR, "div")
```

**Comment by kaliiiiiiiiii** [comment]
> > let's close that issue then
> 
> no, this would be a nice feature
> 
> this only breaks because chromium removed it using more javascript is just an implementation detail
> 
> ```python
> div = await driver.find_element(By.CSS_SELECTOR, "iframe /deep/ div")
> ``

well you can open a PR on that if you want:) Don't really have the time to implement that tbh.

> > `await elem.shadow`
> 
> for my taste, this should be even simpler
> 
> ```diff
> -  (await iframe.shadow).find_element
> +  iframe.find_element
> ```

mhh yeah simpler, but also leads to unclear behaviour, right?
For example the order of the child elemets, etc.

> or call it "document", because thats what it is
> 
> ```diff
> -  (await iframe.shadow).find_element
> +  (await iframe.document).find_element
> ```

mhh I'd prefer shaddow thb. I'd say It's more clear what's meant with it. So similar to `elem.shadowRoot` in JS
