### ISSUE TITLE
[Feature] Read the Docs Configuration and Setup 

### ISSUE THREAD

**Issue by mahmoudamr512** [kaliiiiiiiiii/Selenium-Driverless#166]
Would it be acceptable if I started to create a PR for a ReadTheDocs here and add the relevant documentation? This project documentation is still a little bit hard to navigate :D and I was having trouble going around it

**Comment by kaliiiiiiiiii** [comment]
You can open a PR ofc. I'll review it then.
Please make sure to develop on the "dev" branch. Recently added a lot of docstrings there
