### ISSUE TITLE
`driver.get_cookies()` is outdated.

### ISSUE THREAD

**Issue by limtis0** [kaliiiiiiiiii/Selenium-Driverless#167]
Calling `driver.get_cookies()` results in `cdp_socket.exceptions.CDPError: {'code': -32601, 'message': "'Page.getCookies' wasn't found"}`.
The solution would be using `Network` instead of `Page`, I suppose.

https://chromedevtools.github.io/devtools-protocol/1-3/Network/#method-getCookies

**Comment by kaliiiiiiiiii** [comment]
use the newest version
