### ISSUE TITLE
`webdriver.Chrome` constructor can hang forever

### ISSUE THREAD

**Issue by milahu** [kaliiiiiiiiii/Selenium-Driverless#170]
not sure why exactly, but...
`webdriver.Chrome` can hang forever if the chrome executable is broken

the `timeout` parameter should also apply to the constructor

https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/3a3133c3c557e968cf9a35313e354da331bf91a8/src/selenium_driverless/webdriver.py#L61-L70

currently im hacking on the chrome executable
so the chrome in $PATH can be a wrapper script like

```sh
#!/bin/sh

sleep 9999999

exec /actual/path/to/chrome
```

**Comment by kaliiiiiiiiii** [comment]
hmm no way
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/3a3133c3c557e968cf9a35313e354da331bf91a8/src/selenium_driverless/webdriver.py#L216-L226 shouldn't ever be blocking to my knowledge. 

next thing is https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/3a3133c3c557e968cf9a35313e354da331bf91a8/src/selenium_driverless/webdriver.py#L246-L248

https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/3a3133c3c557e968cf9a35313e354da331bf91a8/src/selenium_driverless/types/base_target.py#L68-L75

Actually - maybe that while should have a timeout?👀👀👀👀👀👀 (that stuff gets first called at https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/3a3133c3c557e968cf9a35313e354da331bf91a8/src/selenium_driverless/webdriver.py#L253)

**Comment by kaliiiiiiiiii** [comment]
> the `timeout` parameter should also apply to the constructor

well it's actually only meant for the startup haha
