### ISSUE TITLE
Directory Clean conditions set wrong

### ISSUE THREAD

**Issue by UnknownBaronX** [kaliiiiiiiiii/Selenium-Driverless#174]
My aim is to remain directories an reuse driver sessions.

Therefore I was creating custom directories:

```
options = webdriver.ChromeOptions()
options.add_argument(f'--user-data-dir={profile_path}')'
driver = await webdriver.Chrome(options=options)
```

To remain directories I was using as documented the _clean_dirs_ flag:
`driver.quit(clean_dirs=False)`

Apparently the directories did get cleaned even when setting the  flag.

When setting driver option to remain dirs globally it doesnt work either
`options.auto_clean_dirs = False
`

Only i combination it remains directories:
```
options = webdriver.ChromeOptions()
options.add_argument(f'--user-data-dir={profile_path}')'
options.auto_clean_dirs = False
driver = await webdriver.Chrome(options=options)
await driver.get('about:blank')
await driver.quit(clean_dirs=False)
```

**Comment by kaliiiiiiiiii** [comment]
thx, will look into

**Comment by kaliiiiiiiiii** [comment]
Pretty sure that's due to https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/b39b2550e9baf243ab21eb1f5c7f145a1b233b3b/src/selenium_driverless/webdriver.py#L286-L287

Will be fixed in the next release
