### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Bllacky** [kaliiiiiiiiii/Selenium-Driverless#178]
It would be nice to have Firefox support.

**Comment by Bllacky** [comment]
Understood!

**Comment by milahu** [comment]
that would require porting [geckodriver](https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver) from rust to python ...

throwing `src/main.rs` at [codingfleet.com/code-converter](https://codingfleet.com/code-converter/python/) i get [main.rs.py.gz](https://github.com/user-attachments/files/15874765/main.rs.py.gz)
good luck with the rest ; )

**Comment by kaliiiiiiiiii** [comment]
> that would require porting [geckodriver](https://hg.mozilla.org/mozilla-central/file/tip/testing/geckodriver) from rust to python ...
> 
> throwing `src/main.rs` at [codingfleet.com/code-converter](https://codingfleet.com/code-converter/python/) i get [main.rs.py.gz](https://github.com/user-attachments/files/15874765/main.rs.py.gz) good luck with the rest ; )

@milahu uh nope I disagree
In fact, firefox support might even be doable with minimal modification to driverless.
See https://firefox-source-docs.mozilla.org/remote/cdp/
