### ISSUE TITLE
abrahamjuliot.github.io/creepjs low trust factor

### ISSUE THREAD

**Issue by FreeM1ne** [kaliiiiiiiiii/Selenium-Driverless#179]
Surprisingly, the undetected playwright patch has a much higher level of trust than other browser management solutions
https://abrahamjuliot.github.io/creepjs/

**Comment by kaliiiiiiiiii** [comment]
Yeah I did notice that as well. Really couldn't figure out why tho:(

Does this apply for new (incognito) contexts with driverless as well?

**Comment by FreeM1ne** [comment]
nope

**Comment by FreeM1ne** [comment]
What cookie formats does your driver accept?

**Comment by kaliiiiiiiiii** [comment]
> What cookie formats does your driver accept?

see https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-Cookie

**Comment by kaliiiiiiiiii** [comment]
Driverless
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/89038706/8f601746-a707-411e-8294-3f25ae7759dd)
undetected-playwright-python
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/89038706/921c66c9-856b-471d-97d8-7049f97637af)

On Win10, Google-Chrome-123

<details>
  <summary>Script used</summary>
  
  ```python
  from selenium_driverless import webdriver
from undetected_playwright.async_api import async_playwright, Playwright
import asyncio


async def run_pw():
    async with async_playwright() as playwright:
        args = ["--start-maximized"]

        # disable navigator.webdriver:true flag
        args.append("--disable-blink-features=AutomationControlled")
        browser = await playwright.chromium.launch(headless=False,args=args, channel="chrome")
        page = await browser.new_page()
        await page.goto("https://abrahamjuliot.github.io/creepjs/")
        while True:
            await asyncio.sleep(1)


async def run_driverless():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        context = await driver.new_context()
        await context.maximize_window()

        await context.get("https://abrahamjuliot.github.io/creepjs/")
        while True:
            await asyncio.sleep(1)


async def main():
    await asyncio.gather(run_pw(), run_driverless())


asyncio.run(main())
  ```
</details>

@FreeM1ne Do you get similar results?

In the meantime, I'll close this as 4% more or less don't seem that relevant to me
