### ISSUE TITLE
Add mouse display in the browser

### ISSUE THREAD

**Issue by FreeM1ne** [kaliiiiiiiiii/Selenium-Driverless#180]
Add mouse display in the browser

**Comment by kaliiiiiiiiii** [comment]
No haha, that would make it technically detectable:)

**Comment by FreeM1ne** [comment]
Why? Just a visual display why should it be detectable?

**Comment by kaliiiiiiiiii** [comment]
> Why? Just a visual display why should it be detectable?

Display would be a canvas embedded into DOM.
The page could detect that Canvas element in the html.
