### ISSUE TITLE
simple site easy detected

### ISSUE THREAD

**Issue by FreeM1ne** [kaliiiiiiiiii/Selenium-Driverless#181]
accept_cookie
write_mail
click_send
it's detect me
https://www.kleinanzeigen.de/m-passwort-vergessen.html

**Comment by FreeM1ne** [comment]
Detects click / text input methods, because if you open the browser and type by hand everything is ok

**Comment by kaliiiiiiiiii** [comment]
Im aware of this issue.
This is a part of https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/94 , therefore closing as dublicate
