### ISSUE TITLE
execute_cdp_cmd Not support `Network.enable` ?

### ISSUE THREAD

**Issue by langhuihui** [kaliiiiiiiiii/Selenium-Driverless#186]
cdp_socket.exceptions.CDPError: {'code': -32601, 'message': "'Network.enable' wasn't found"}

**Comment by kaliiiiiiiiii** [comment]
It does, just depending on the target.
`driver.current_target` for example.
Just per-target and not on `driver.base_target` over the whole browser.

**Comment by langhuihui** [comment]
Thank U very much!
