### ISSUE TITLE
how can i use a normal user dir

### ISSUE THREAD

**Issue by maximalidealg** [kaliiiiiiiiii/Selenium-Driverless#189]
i want to use my own chrome's user dir, because there my extents and history,how can i do it? plz

**Comment by kaliiiiiiiiii** [comment]
`options.user_data_dir = False`
Will be put into the documentation.

Note: In future, please ONLY open issues when there's a bug. For questions, you can open a discussion.

**Comment by kaliiiiiiiiii** [comment]
Note: this only works with the newest version.
