### ISSUE TITLE
page source is not working correctly

### ISSUE THREAD

**Issue by FreeM1ne** [kaliiiiiiiiii/Selenium-Driverless#194]
it only returns the current frame

**Comment by FreeM1ne** [comment]
how can I run through all the current Frames?

**Comment by kaliiiiiiiiii** [comment]
> it only returns the current frame

I'd consider that to be expected

**Comment by FreeM1ne** [comment]
page source != frame source

**Comment by kaliiiiiiiiii** [comment]
> page source != frame source

Yes, I'm aware of.
But that's as well how selenium works.

**Comment by kaliiiiiiiiii** [comment]
@FreeM1ne Will be implemented with `driver.snapshot->str` (mhtml)
