### ISSUE TITLE
Same script, different behaviour Linux/Windows

### ISSUE THREAD

**Issue by javinair** [kaliiiiiiiiii/Selenium-Driverless#195]
Hello,

I'm developing a little Python script to fetch data from bet365.

That script works nicely on Windows, using `selenium_driverless 1.7.1`. I've moved that script to a Linux machine and, using the same script, and same requirements.txt (moved from the Windows machine to the Linux machine), I'm not able to reach bet365. It shows me the page saying that current markets are not available (I know that screen is shown when I've been detected).

This is the way I'm using your Chrome selenium_driverless (and it works perfect on Windows):
```
    options = webdriver.ChromeOptions()    
    async with webdriver.Chrome(options=options) as driver:
    [...]
    await driver.get('https://www.bet365.es/#/AS/B18/')
```
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/44604000/33166855-22ad-4c6d-8427-e2091aaa19e8)

```
Chromium Versión 114.0.5735.133 (Build oficial) for Linux Mint (64 bits)
Chrome Versión 123.0.6312.86 (Build oficial) (64 bits)
Linux Mint 21.04
```

Is there anything I should keep in mind in order to make it work on Linux?

Thanks in advance.

**Comment by kaliiiiiiiiii** [comment]
Yep, that's fingerprinting.
Which driverless does not cover yet
