### ISSUE TITLE
turnstile click detected

### ISSUE THREAD

**Issue by ruslanx3m** [kaliiiiiiiiii/Selenium-Driverless#20]
I need to move mouse and click on checkbox (turnstile) ... I tried using ActionChains got error ...
https://nopecha.com/demo/turnstile - here demo 
How ca I do ?
if I click using javascript will not pass ...

**Comment by kaliiiiiiiiii** [comment]
I'll have a look at it, thanks for submissing this issue

**Comment by ruslanx3m** [comment]
**thank you**, because I'm stuck on this, without this it's useless for me, will be nice if you will resolve this part if is possible .. I found a solution but it use real mouse, so I can not do anything else on my pc at same time .. or run in more than 1  threads

**Comment by kaliiiiiiiiii** [comment]
@ruslanx3m 
Check the following:
```python
from selenium_driverless.sync import webdriver
from selenium_driverless.types.by import By

options = webdriver.ChromeOptions()
options.add_argument("--auto-open-devtools-for-tabs")
with webdriver.Chrome(options=options) as driver:
    driver.get("chrome://version")
    elem = driver.find_element(By.XPATH, '//*[@id="t"]/body')
    script = """
    document.documentElement.addEventListener("click", (event) => {
        throw new Error()
    })
    """
    driver.execute_script(script)

    # with `HTMLElement.dispatchEvent()`
    elem.click()

    # with `HTMLElement.click()` (bad!)
    elem.execute_script("this.click()")

    # with input domain
    x = 100
    y = 100
    driver.execute_cdp_cmd("Input.dispatchMouseEvent", {"type":"mousePressed", "x":x, "y":y, "button":"left", "clickCount":1})
    driver.implicitly_wait(0.1)
    driver.execute_cdp_cmd("Input.dispatchMouseEvent", {"type": "mouseReleased", "x": x, "y": y, "button":"left","clickCount":1})
    input("open console, click manually and compare errors")
```

=> `Input.dispatchMouseEvent` looks the same as manual clicking
=> going to implement ActionChains this way

**Comment by ruslanx3m** [comment]
I use driverless to click on turnstile captcha checkbox ... but how ? sorry if so... but can you provide a working example for https://nopecha.com/demo/turnstile ? python selenium I use for a week..

**Comment by ruslanx3m** [comment]
I can confirm that these commands work with turnstile captcha:
```
driver.execute_cdp_cmd("Input.dispatchMouseEvent", {"type":"mousePressed", "x":x, "y":y, "button":"left", "clickCount":1})
driver.execute_cdp_cmd("Input.dispatchMouseEvent", {"type":"mouseReleased", "x":x, "y":y, "button":"left", "clickCount":1})
driver.execute_cdp_cmd("Input.dispatchMouseEvent", {"type":"mouseMoved", "x":x, "y":y, "button":"left", "clickCount":1})
```

**Comment by ruslanx3m** [comment]
resolved

**Comment by kaliiiiiiiiii** [comment]
@ruslanx3m That's great to know, implementing at https://github.com/kaliiiiiiiiii/Selenium-Driverless/tree/dev#pointer-interaction btw (dev)

**Comment by alimayorru** [comment]
Please i'm finding it difficult clicking on the button, the method don't have a place to input the button variable.
please i will need a guide clicking on the google search button.

here's my code
`import time

from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium_driverless.webdriver import ChromeOptions
from selenium_driverless.types.by import By
import random


profile = profiles.Windows()  # or .Android


options = ChromeOptions()


driver = Chrome(profile, options=options, driverless_options=True)

driver.get("https://www.google.com")
time.sleep(5)

search_box = driver.find_element("name", "q")

search_box.send_keys("letter")
time.sleep(2)
search = driver.find_element("name", "btnK")

x = 100
y = 100
driver.execute_cdp_cmd("Input.dispatchMouseEvent",
                       {"type": "mousePressed", "x": x, "y": y, "button": "left", "clickCount": 1})
driver.implicitly_wait(0.1)
driver.execute_cdp_cmd("Input.dispatchMouseEvent",
                       {"type": "mouseReleased", "x": x, "y": y, "button": "left", "clickCount": 1})


time.sleep(7)

driver.quit()  # Execute on the End!
`

**Comment by kaliiiiiiiiii** [comment]
@alimayorru There's no need for that anymore, the current version `elem.click()` does that by default

**Comment by alimayorru** [comment]
> no need for that anymore, the current version `elem.click()` does that by default

does it do just like actionchains?

**Comment by kaliiiiiiiiii** [comment]
Yeah kind of, altho ActionChains don't really exist with Selenium-Driverless

**Comment by alimayorru** [comment]
okay thanks

**Comment by alimayorru** [comment]
please with elem.click() how can i click_and_hold and moved by offset x y?

**Comment by alimayorru** [comment]
@kaliiiiiiiiii please help me out, i'm stuck with that

**Comment by alimayorru** [comment]
Ok i will wait for you, i'm new to all this, i don't understand what you mean by  "install & clone from the dev-branch"
