### ISSUE TITLE
Chromium Failed to load mv3_extension on linux

### ISSUE THREAD

**Issue by namtacs** [kaliiiiiiiiii/Selenium-Driverless#202]
System: Debian Linux trixie
Fresh chromium(snap 123.0.6312.105) and Selenium-Driverless installs. Tried Selenium-Driverless current dev and pypi versions.

On load, chromium displays this error: `Failed to load extension from: /home/user/.local/lib/python3.11/site-packages/selenium_driverless/files/mv3_extension. Manifest is not valid JSON.  Can't read file.` in a popup
After a few seconds the popup closes and the driver continues working as normal (on first look).

selenium_driverless/files/mv3_extension is a folder(NOT A ZIP) and contains a manifest.json and a script.

**Comment by namtacs** [comment]
Just realized this project is chrome only 😥️. But with google chrome installed, it works perfectly. 
This issue looks like a small fix away from being solved. Maybe someone can fix it.

**Comment by kaliiiiiiiiii** [comment]
@namtacs Have you checked if it succeeds when changing the permissions to rw?

**Comment by namtacs** [comment]
**It's already rw:**
mw3_extension folder: **drwx**
manifest and script: **-rw-**         Changing to -rwx doesn't help.

**Comment by kaliiiiiiiiii** [comment]
> **It's already rw:** mv3_extension folder: **drwx** manifest and script: **-rw-** Changing to -rwx doesn't help.
> 
> On [this StackOverflow answer](https://stackoverflow.com/questions/16511384/using-extensions-with-selenium-python/51528329#51528329) it says to zip it. I tried zipping only the files and putting it under the name of the folder (mv3_extension without a file ext.). And I tried zipping the entire folder and putting it under the same name.

well it shouldn't even matter - driverless supports both. 
Question is more why `Manifest is not valid JSON`

**Comment by namtacs** [comment]
same
i don't see you did any related commits

**Comment by kaliiiiiiiiii** [comment]
don't think that's gonna be fixed.
Can't relroduce => can't fix that
