### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by nandish486** [kaliiiiiiiiii/Selenium-Driverless#203]
Is there anything equivalent to auto wait just like undetected playwright's page.wait_for_event('domcontentloaded'),

I tried

```
from selenium_driverless.sync import webdriver

options = webdriver.ChromeOptions()
with webdriver.Chrome(options=options) as driver:
    driver.get('http://nowsecure.nl#relax')
    driver.sleep(0.5)
    driver.wait_for_cdp("Page.domContentEventFired", timeout=15)

    title = driver.title
    url = driver.current_url
    source = driver.page_source
    print(title)
    
```
    
 but it raises time out error, the site is loaded and it passed cf turnstile, but it won't close automatically, like it supposed to do without raising timeout errors.

**Comment by kaliiiiiiiiii** [comment]
@nandish486 Please don't open issues with poor description or without there being an actual bug

**Comment by nandish486** [comment]
> The feature you're looking for is generally available (async-only) using with
> 
> ```python
> async for iframe in await driver.get_cdp_event_iter("Page.frameNavigated"):
>    print(iframe)
> ```
> 
> I believe

page not have any iframe, i want page to load wait , just like "domContentLoaded"

**Comment by nandish486** [comment]
> > > The feature you're looking for is generally available (async-only) using with
> > > ```python
> > > async for iframe in await driver.get_cdp_event_iter("Page.frameNavigated"):
> > >    print(iframe)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I believe
> > 
> > 
> > page not have any iframe, i want page to load wait , just like "domContentLoaded"
> 
> well that's what `driver.get(` already does. Unless you specify `wait_load=False`

it just exits, not wait for complete page to load

**Comment by kaliiiiiiiiii** [comment]
> it just exits, not wait for complete page to load

Well then there isn't a general way => wait for the relevant elements to appear
