### ISSUE TITLE
How to propose text on elements

### ISSUE THREAD

**Issue by hn315** [kaliiiiiiiiii/Selenium-Driverless#211]
How to propose text on elements？My following code reported an error. May I ask how to modify it
`msg = await driver.find_element(By.XPATH, '/html/body/div[1]/div/div/div/div[2]/div/div/form/div[5]/span', timeout=10).text

print(msg)`

**Comment by kaliiiiiiiiii** [comment]
use [WebElement.execute_script](https://kaliiiiiiiiii.github.io/Selenium-Driverless/api/WebELement/#selenium_driverless.types.webelement.WebElement.execute_script) with `obj.textContent= "some text"`

**Comment by hn315** [comment]
@kaliiiiiiiiii 
Thank you .Finally succeeded with your code. I'm a beginner and don't know how to use it, sorry.
