### ISSUE TITLE
How to propose text on elements 

### ISSUE THREAD

**Issue by hn315** [kaliiiiiiiiii/Selenium-Driverless#212]
My following code reported an error.     Please help me directly modify the following code to display the text

 msg = await driver.find_element(By.XPATH, '//*[@id="outer"]/table/tbody/tr/td/table[1]/tbody/tr[5]/td[2]', timeout=10).textContent
        print(msg)

Thanks

**Comment by kaliiiiiiiiii** [comment]
@hn315 please no duplicate issues in here!
Elsewhise I'll have to block you.

**Comment by kaliiiiiiiiii** [comment]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/211
