### ISSUE TITLE
How to package py files

### ISSUE THREAD

**Issue by hn315** [kaliiiiiiiiii/Selenium-Driverless#213]
I used the following command to package the py file, but the generated exe file executed incorrectly. How can I run the packaging program correctly?Please modify the command for me.Thanks

pyinstaller --onefile --hidden-import=selenium_driverless C:\myexe\index.py

**Comment by hn315** [comment]
> use `--collect-data=selenium_driverless`

@kaliiiiiiiiii 
I used 'pyinstaller --onefile  --collect-data=selenium_driverless  C:\myexe\index.py' to package the py file, but the generated exe file executed incorrectly.  Thanks
----------------------------------------------------------------------------------------------------
C:\myexe>pyinstaller --onefile  --collect-data=selenium_driverless  C:\myexe\index.py
217 INFO: PyInstaller: 6.4.0, contrib hooks: 2024.1
217 INFO: Python: 3.10.11
223 INFO: Platform: Windows-10-10.0.17763-SP0
223 INFO: wrote C:\myexe\index.spec
243 INFO: Extending PYTHONPATH with paths
['C:\\myexe']
447 INFO: Appending 'datas' from .spec
448 INFO: checking Analysis
448 INFO: Building Analysis because Analysis-00.toc is non existent
448 INFO: Initializing module dependency graph...
449 INFO: Caching module graph hooks...
458 INFO: Analyzing base_library.zip ...
1031 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
1067 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
1809 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
2414 INFO: Caching module dependency graph...
2499 INFO: Running Analysis Analysis-00.toc
2499 INFO: Looking for Python shared library...
2503 INFO: Using Python shared library: C:\Users\PC02\AppData\Local\Programs\Python\Python310\python310.dll
2503 INFO: Analyzing C:\myexe\index.py
2554 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
2619 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
2713 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
3002 INFO: Loading module hook 'hook-websockets.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
3406 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\_pyinstaller'...
3699 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
3761 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
4584 INFO: Loading module hook 'hook-scipy.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
4649 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
4900 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
6094 INFO: Processing pre-safe import module hook distutils from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-distutils.py'.
6095 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
6389 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
6421 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
6546 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
7311 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
7960 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
8303 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
8913 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
10035 INFO: Loading module hook 'hook-orjson.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10575 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10613 INFO: Processing module hooks...
10615 INFO: Loading module hook 'hook-zoneinfo.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10628 INFO: Loading module hook 'hook-selenium.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
10803 WARNING: Hidden import "tzdata" not found!
10811 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
11097 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
11098 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
11099 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
11116 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
11470 INFO: Loading module hook 'hook-setuptools._distutils.command.check.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
11602 INFO: Performing binary vs. data reclassification (19 entries)
11615 INFO: Looking for ctypes DLLs
11646 INFO: Analyzing run-time hooks ...
11651 INFO: Including run-time hook 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
11653 INFO: Including run-time hook 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
11655 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
11656 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
11657 INFO: Including run-time hook 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
11659 INFO: Including run-time hook 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
11660 INFO: Including run-time hook 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
11681 INFO: Looking for dynamic libraries
C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py:194: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
12463 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\scipy.libs', 'C:\\Users\\PC02\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\numpy.libs']
12464 INFO: Extra DLL search directories (PATH): []
13586 INFO: Warnings written to C:\myexe\build\index\warn-index.txt
13674 INFO: Graph cross-reference written to C:\myexe\build\index\xref-index.html
13716 INFO: checking PYZ
13716 INFO: Building PYZ because PYZ-00.toc is non existent
13717 INFO: Building PYZ (ZlibArchive) C:\myexe\build\index\PYZ-00.pyz
14649 INFO: Building PYZ (ZlibArchive) C:\myexe\build\index\PYZ-00.pyz completed successfully.
14674 INFO: checking PKG
14675 INFO: Building PKG because PKG-00.toc is non existent
14676 INFO: Building PKG (CArchive) index.pkg
31016 INFO: Building PKG (CArchive) index.pkg completed successfully.
31021 INFO: Bootloader C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
31021 INFO: checking EXE
31021 INFO: Building EXE because EXE-00.toc is non existent
31021 INFO: Building EXE from EXE-00.toc
31022 INFO: Copying bootloader EXE to C:\myexe\dist\index.exe
31069 INFO: Copying icon to EXE
31112 INFO: Copying 0 resources to EXE
31112 INFO: Embedding manifest in EXE
31157 INFO: Appending PKG archive to EXE
31191 INFO: Fixing EXE headers
31589 INFO: Building EXE from EXE-00.toc completed successfully.
----------------------------------------------------------------------------------------

C:\myexe\dist>index.exe
Traceback (most recent call last):
  File "index.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "selenium_driverless\webdriver.py", line 40, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "selenium_driverless\input\pointer.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "selenium_driverless\scripts\geometry.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\interpolate\__init__.py", line 167, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\interpolate\_interpolate.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "scipy\special\__init__.py", line 777, in <module>
  File "scipy\\special\\_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._cdflib'
[2412] Failed to execute script 'index' due to unhandled exception!

C:\myexe\dist>

**Comment by kaliiiiiiiiii** [comment]
> > use `--collect-data=selenium_driverless`
> 
> @kaliiiiiiiiii I used 'pyinstaller --onefile --collect-data=selenium_driverless C:\myexe\index.py' to package the py file, but the generated exe file executed incorrectly. Thanks ########################################################### C:\myexe>pyinstaller --onefile --collect-data=selenium_driverless C:\myexe\index.py 217 INFO: PyInstaller: 6.4.0, contrib hooks: 2024.1 217 INFO: Python: 3.10.11 223 INFO: Platform: Windows-10-10.0.17763-SP0 223 INFO: wrote C:\myexe\index.spec 243 INFO: Extending PYTHONPATH with paths ['C:\myexe'] 447 INFO: Appending 'datas' from .spec 448 INFO: checking Analysis 448 INFO: Building Analysis because Analysis-00.toc is non existent 448 INFO: Initializing module dependency graph... 449 INFO: Caching module graph hooks... 458 INFO: Analyzing base_library.zip ... 1031 INFO: Loading module hook 'hook-heapq.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 1067 INFO: Loading module hook 'hook-encodings.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 1809 INFO: Loading module hook 'hook-pickle.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 2414 INFO: Caching module dependency graph... 2499 INFO: Running Analysis Analysis-00.toc 2499 INFO: Looking for Python shared library... 2503 INFO: Using Python shared library: C:\Users\PC02\AppData\Local\Programs\Python\Python310\python310.dll 2503 INFO: Analyzing C:\myexe\index.py 2554 INFO: Loading module hook 'hook-platform.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 2619 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 2713 INFO: Loading module hook 'hook-xml.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 3002 INFO: Loading module hook 'hook-websockets.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'... 3406 INFO: Loading module hook 'hook-numpy.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\Lib\site-packages\numpy\_pyinstaller'... 3699 INFO: Loading module hook 'hook-difflib.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 3761 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 4584 INFO: Loading module hook 'hook-scipy.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 4649 INFO: Loading module hook 'hook-pycparser.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'... 4900 INFO: Loading module hook 'hook-setuptools.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 6094 INFO: Processing pre-safe import module hook distutils from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-distutils.py'. 6095 INFO: Processing pre-find module path hook distutils from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\pre_find_module_path\hook-distutils.py'. 6389 INFO: Loading module hook 'hook-distutils.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 6421 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 6546 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 7311 INFO: Loading module hook 'hook-packaging.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 7960 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 8303 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 8913 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 10035 INFO: Loading module hook 'hook-orjson.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'... 10575 INFO: Loading module hook 'hook-platformdirs.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'... 10613 INFO: Processing module hooks... 10615 INFO: Loading module hook 'hook-zoneinfo.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'... 10628 INFO: Loading module hook 'hook-selenium.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks'... 10803 WARNING: Hidden import "tzdata" not found! 10811 INFO: Processing pre-safe import module hook win32com from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\_pyinstaller_hooks_contrib\hooks\pre_safe_import_module\hook-win32com.py'. 11097 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 11098 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 11099 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 11116 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 11470 INFO: Loading module hook 'hook-setuptools._distutils.command.check.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 11602 INFO: Performing binary vs. data reclassification (19 entries) 11615 INFO: Looking for ctypes DLLs 11646 INFO: Analyzing run-time hooks ... 11651 INFO: Including run-time hook 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_inspect.py' 11653 INFO: Including run-time hook 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgutil.py' 11655 INFO: Processing pre-find module path hook _pyi_rth_utils from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\pre_find_module_path\hook-_pyi_rth_utils.py'. 11656 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks'... 11657 INFO: Including run-time hook 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py' 11659 INFO: Including run-time hook 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_setuptools.py' 11660 INFO: Including run-time hook 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_pkgres.py' 11681 INFO: Looking for dynamic libraries C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py:194: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47. **import**(package) 12463 INFO: Extra DLL search directories (AddDllDirectory): ['C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy.libs', 'C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy.libs'] 12464 INFO: Extra DLL search directories (PATH): [] 13586 INFO: Warnings written to C:\myexe\build\index\warn-index.txt 13674 INFO: Graph cross-reference written to C:\myexe\build\index\xref-index.html 13716 INFO: checking PYZ 13716 INFO: Building PYZ because PYZ-00.toc is non existent 13717 INFO: Building PYZ (ZlibArchive) C:\myexe\build\index\PYZ-00.pyz 14649 INFO: Building PYZ (ZlibArchive) C:\myexe\build\index\PYZ-00.pyz completed successfully. 14674 INFO: checking PKG 14675 INFO: Building PKG because PKG-00.toc is non existent 14676 INFO: Building PKG (CArchive) index.pkg 31016 INFO: Building PKG (CArchive) index.pkg completed successfully. 31021 INFO: Bootloader C:\Users\PC02\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe 31021 INFO: checking EXE 31021 INFO: Building EXE because EXE-00.toc is non existent 31021 INFO: Building EXE from EXE-00.toc 31022 INFO: Copying bootloader EXE to C:\myexe\dist\index.exe 31069 INFO: Copying icon to EXE 31112 INFO: Copying 0 resources to EXE 31112 INFO: Embedding manifest in EXE 31157 INFO: Appending PKG archive to EXE 31191 INFO: Fixing EXE headers 31589 INFO: Building EXE from EXE-00.toc completed successfully. ##########################################################
> 
> C:\myexe\dist>index.exe Traceback (most recent call last): File "index.py", line 1, in File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "selenium_driverless\webdriver.py", line 40, in File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "selenium_driverless\input\pointer.py", line 8, in File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "selenium_driverless\scripts\geometry.py", line 5, in File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "scipy\interpolate__init__.py", line 167, in File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "scipy\interpolate_interpolate.py", line 10, in File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module File "scipy\special__init__.py", line 777, in File "scipy\special\_ufuncs.pyx", line 1, in init scipy.special._ufuncs ModuleNotFoundError: No module named 'scipy.special._cdflib' [2412] Failed to execute script 'index' due to unhandled exception!
> 
> C:\myexe\dist>

yeah but that's an issue with scipy & pyinstaller
You can look it up, there are workarounds available
