### ISSUE TITLE
EXTENSION IN INCOGNITO METHOD FAILS

### ISSUE THREAD

**Issue by nandish486** [kaliiiiiiiiii/Selenium-Driverless#217]
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/93249676/9e626968-be1b-4f64-9313-5f39be34f6e4)
![image](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/93249676/2c8bede1-8057-4c40-9d0c-2c03f3ff4e05)

```
options = webdriver.ChromeOptions()
options.add_argument('--incognito')
# options.add_argument(f'--user-data-dir={userdata}')
options.add_extension(r'extension')
with webdriver.Chrome(options=options) as driver:
    driver.get('https://nopecha.com/demo/recaptcha', wait_load=True, timeout=10)
    driver.ensure_extensions_incognito_allowed()
    driver.maximize_window()

    driver.sleep(100)
    title = driver.title
    url = driver.current_url
    source = driver.page_source
```

**Comment by kaliiiiiiiiii** [comment]
`enssure_extensions_allowed` is only supported while there is a non-incognito window open

**Comment by nandish486** [comment]
> `enssure_extensions_allowed` is only supported while there is a non-incognito window open

how to use extension in incognito then?

**Comment by kaliiiiiiiiii** [comment]
use `context`s
There's an example in the readme
You can also later close the main context, if you decide that you don't need it anymore

**Comment by nandish486** [comment]
also if there is something like page.route() in playwright, for selenium driverless, cause selenium driverless is better

**Comment by kaliiiiiiiiii** [comment]
> > use `context`s There's an example in the readme You can also later close the main context, if you decide that you don't need it anymore
> 
> i saw it but not satisfied, if we launch normal context is it just incognito version, one without user directory?

yeah, as I said

**Comment by kaliiiiiiiiii** [comment]
> also if there is something like page.route() in playwright, for selenium driverless, cause selenium driverless is better

it's right there in the documentation & readme

**Comment by nandish486** [comment]
> it's right there in the documentation & readme

it not works with sync, is sync support not yet added?

**Comment by kaliiiiiiiiii** [comment]
> > it's right there in the documentation & readme
> 
> it not works with sync, is sync support not yet added?

yep
