### ISSUE TITLE
how to connect selenium driverless package with remote browser like gologin

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [kaliiiiiiiiii/Selenium-Driverless#224]
how to connect selenium driverless package with remote browser like gologin

**Comment by kaliiiiiiiiii** [comment]
`options.debugger_address` I believe. It's right there in the readme.
This is a warning! Do NOT open any issues unless there's an actual bug! Elsewhise I'll have to block you from interacting with this repo.
