### ISSUE TITLE
chrome version error when using driverless package 

### ISSUE THREAD

**Issue by pythondeveloperz** [kaliiiiiiiiii/Selenium-Driverless#225]
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:3500 from session not created: This version of ChromeDriver only supports Chrome version 125 Current browser version is 124.0.6367.78

how can i handle this error how to use an older chrome version rather than the latest one please?

**Comment by kaliiiiiiiiii** [comment]
that error has nothing to do with selenium-driverless

**Comment by pythondeveloperz** [comment]
> that error has nothing to do with selenium-driverless

i dont mean there is a bug on the package but i mean the profile i want to automate it is version 124 and the driver connected with package is  version 125 

i want to know how can i handle the error and make the driver of the package 124 the same of the browser i want to automate it 

this is the code i run it 👍 

`from selenium_driverless import webdriver
import asyncio
import time
from sys import platform
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from gologin import GoLogin
from gologin import getRandomPort



# random_port = get_random_port() # uncomment to use random port

gl = GoLogin({
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NjQ4ZmE3M2ExN2UyNGNiYmUwMzcyM2UiLCJ0eXBlIjoiZGV2Iiwiand0aWQiOiI2NjQ4ZmFjN2I5MDE4Y2Q3ODZmYWE1MzcifQ.qqKCRKqhRByrpxo88Kk1oxPJGzHVO_PScKP0EgVvODI",
	"profile_id": "6648faa2ba44fe9e8864d934",
	# "port": random_port
	})


debugger_address = gl.start()

# specify if you don't want to run remote
# options.add_argument("--remote-debugging-port=2005")
async def main():
    options = webdriver.ChromeOptions()
    options.debugger_address = debugger_address


    async with webdriver.Chrome(options=options) as driver:

      await driver.get('http://nowsecure.nl#relax', wait_load=True)
      gl.stop()
asyncio.run(main())`

and the following is the error appeared to me : 

`Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\pythonProject\driverless.py", line 34, in <module>
    asyncio.run(main())
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\HP\PycharmProjects\pythonProject\driverless.py", line 30, in main
    async with webdriver.Chrome(options=options) as driver:
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 209, in __init__
    self.start_session(capabilities)
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 293, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\HP\PycharmProjects\pythonProject\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:3500
from session not created: This version of ChromeDriver only supports Chrome version 125
Current browser version is 124.0.6367.78
Stacktrace:
	GetHandleVerifier [0x00007FF6CC7622C2+60002]
	(No symbol) [0x00007FF6CC6DCA59]
	(No symbol) [0x00007FF6CC597EDA]
	(No symbol) [0x00007FF6CC5D6242]
	(No symbol) [0x00007FF6CC5D5418]
	(No symbol) [0x00007FF6CC5CA939]
	(No symbol) [0x00007FF6CC6179A4]
	(No symbol) [0x00007FF6CC617000]
	(No symbol) [0x00007FF6CC60C033]
	(No symbol) [0x00007FF6CC5D9657]
	(No symbol) [0x00007FF6CC5DA251]
	GetHandleVerifier [0x00007FF6CCA73E2D+3278285]
	GetHandleVerifier [0x00007FF6CCAC0190+3590448]
	GetHandleVerifier [0x00007FF6CCAB61D0+3549552]
	GetHandleVerifier [0x00007FF6CC811DE6+779654]
	(No symbol) [0x00007FF6CC6E7ACF]
	(No symbol) [0x00007FF6CC6E2EE4]
	(No symbol) [0x00007FF6CC6E3072]
	(No symbol) [0x00007FF6CC6D2C4F]
	BaseThreadInitThunk [0x00007FF91C04257D+29]
	RtlUserThreadStart [0x00007FF91D0CAA48+40]`

**Comment by kaliiiiiiiiii** [comment]
```python
from selenium_driverless import webdriver
import asyncio
import time
from sys import platform
from selenium import webdriver #shaddows driveeless webdriver
from selenium.webdriver.chrome.options import Options
```

you overwrite the variable `webdriver` by importing the selenium one after driverless one.
Also, you can't mix selenium & driverless in mlst cases
