### ISSUE TITLE
[BUG] minimize_window

### ISSUE THREAD

**Issue by yobogs** [kaliiiiiiiiii/Selenium-Driverless#234]
Hi, 

For def minimize_window you have set_window_state("**maximized**").
Need to be **minimized**, No ?

```
async def maximize_window(self) -> None:
        """Maximizes the current window that webdriver is using."""
        await self.set_window_state("maximized")

async def minimize_window(self) -> None:
        """Invokes the window manager-specific 'minimize' operation."""
        await self.set_window_state("maximized")
```

**Comment by kaliiiiiiiiii** [comment]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/348b95dbb0025d1343fc3c6ade3540129269ae37/src/selenium_driverless/types/context.py#L518-L520

yep, I can confirm this bug//typo.
Will fix it for the next release, thanks.
