### ISSUE TITLE
Bug: minimize_window function maximizes the window instead of minimizing it

### ISSUE THREAD

**Issue by supritobiswas** [kaliiiiiiiiii/Selenium-Driverless#240]
https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/348b95dbb0025d1343fc3c6ade3540129269ae37/src/selenium_driverless/webdriver.py#L978

**Expected Behavior:**
The function should minimize the browser window.
**Actual Behavior:**
The function maximizes the browser window.

Found the workaround, set_window_state('minimized'), but the bug fix would be nice!

**Comment by kaliiiiiiiiii** [comment]
#234 duplicate
