### ISSUE TITLE
Page.domContentEventFired ERROR 

### ISSUE THREAD

**Issue by ahmedabdelhamedz** [kaliiiiiiiiii/Selenium-Driverless#246]
> from selenium_driverless import webdriver
> from selenium_driverless.types.by import By
> import asyncio
> 
> 
> async def main():
>     options = webdriver.ChromeOptions()
>     async with webdriver.Chrome(options=options) as driver:
>         await driver.get('https://nowsecure.nl#relax', wait_load=True)
>         await driver.sleep(0.5)
>         await driver.wait_for_cdp("Page.domContentEventFired",timeout=60)
>         print(await driver.title)
> 
> 
> asyncio.run(main())

await driver.wait_for_cdp("Page.domContentEventFired",timeout=60)     THIS LINE not work automatically i tried to increase the time out more than 1 min the same result but when i write any link by myself in the browser it work can i know the reason

**Comment by kaliiiiiiiiii** [comment]
just leave it out then.

**Comment by kaliiiiiiiiii** [comment]
@ahmedabdelhamedz please don't open any further issues unless there's an actual bug!
Otherwise, I'll have to block you from interacting with this repository.

**Comment by ahmedabdelhamedz** [comment]
> @ahmedabdelhamedz please don't open any further issues unless there's an actual bug! Otherwise, I'll have to block you from interacting with this repository.

okay bro please can you send me the reference of documenting for driverless becuase i didnt find it in the files please
