### ISSUE TITLE
How can I use mouse click-and-hold and drag in selenium-driverless

### ISSUE THREAD

**Issue by tuandoan1608** [kaliiiiiiiiii/Selenium-Driverless#252]
Hello,

How can I use mouse click-and-hold and drag in selenium-driverless?
Do you have any example code illustrating that?
Thank you.

**Comment by kaliiiiiiiiii** [comment]
Mouse down, them move, then up
Simple as that

**Comment by kaliiiiiiiiii** [comment]
Please don't open any further issues unless there's an actual bug
