### ISSUE TITLE
Captcha appering using selenium driverless

### ISSUE THREAD

**Issue by userbox020** [kaliiiiiiiiii/Selenium-Driverless#253]
But when i launch the chrome browser manually and browse google for do a search it doesnt ask for captcha

**Comment by kaliiiiiiiiii** [comment]
You might wanna try using CDP-patches together with driverless.

**Comment by userbox020** [comment]
> You might wanna try using CDP-patches together with driverless.

thanks bro going to try, seems like waiting 3 hours the ip get delisted for captchas again on google
