### ISSUE TITLE
Removing headers

### ISSUE THREAD

**Issue by Stavmeister** [kaliiiiiiiiii/Selenium-Driverless#256]
Hi does anyone know how I can remove headers?

Tried using this with no success:
async def set_headers_and_omit(driver, headers, headers_omission):
    if headers:
        headers_dict = {header.split(':')[0].strip(): header.split(':')[1].strip() for header in headers}
        try:
            await driver.execute_cdp_cmd("Network.setExtraHTTPHeaders", {"headers": headers_dict})
            print(f"Set headers: {headers_dict}")
        except Exception as e:
            print(f"Failed to set headers: {e}")

    if headers_omission:
        try:
            await driver.execute_cdp_cmd("Network.clearRequestHeaders", {"headers": headers_omission})
            print(f"Omitted headers: {headers_omission}")
        except Exception as e:
            print(f"Failed to omit headers: {e}")
            
Adding headers worked.

**Comment by kaliiiiiiiiii** [comment]
Just use request interception - see documentation
