### ISSUE TITLE
I can't access the iframe using find_element

### ISSUE THREAD

**Issue by larry-ct** [kaliiiiiiiiii/Selenium-Driverless#259]
iframes = await driver.find_elements(By.TAG_NAME,"iframe")
![image](https://github.com/user-attachments/assets/5a714f61-3a45-44d0-bf4e-23dd7caf3aaf)

**Comment by kaliiiiiiiiii** [comment]
JSNodeList is a list of the found iframes. Don't see an issue with that?

The length of the list being 0 likely mean that no iframe is on that page at this specific point in time. 

Also, please next time provide information on how to reproduce the issue. This is a warning.
