### ISSUE TITLE
Suport for SSL Context

### ISSUE THREAD

**Issue by rafaelgdn** [kaliiiiiiiiii/Selenium-Driverless#265]
Hello everyone,

I'm facing an issue when using a residential proxy with Selenium Driverless. Whenever I open any URL, I always get "insecure content" warnings. I've tried adding these two arguments to Chrome options:

"--ignore-certificate-errors"
"--ignore-ssl-errors"

However, this didn't solve the problem. I checked proxy provider documentation, and it mentions that I need to send an SSL certificate. I've downloaded the ca.crt file, but I couldn't make it work.

```
import ssl

context = ssl.create_default_context()
context.load_verify_locations('caminho/para/o/certificado.srt')
```

How can i use that context with selenium_driverless?

Can anyone provide some guidance on how to properly set up the SSL certificate with Selenium Driverless when using Bright Data's residential proxy? Any help would be greatly appreciated.

Thank you in advance!

**Comment by Toxenskiy** [comment]
Start the browser (in the normal way) and add the certificate through settings and the problem will be solved

**Comment by kaliiiiiiiiii** [comment]
Don't think this is possible/feasible at browser-level for chrome.
workarounds might be to:
- add the certificates at OS-level
- `options.add_argument("--ignore-certificate-errors")

therefore closing for now
