### ISSUE TITLE
[feature request] `WebElement` interaction enhancements

### ISSUE THREAD

**Issue by Acanis87** [kaliiiiiiiiii/Selenium-Driverless#271]
For your WebElement.click() I would really love to see a new parameter "total_clicks". I have some cases where I need 2 clicks on the element and to debug, I often want the cursor to move to the element without the click (so total_clicks = 0) and it would be cool to just change 1 parameter after debugging. :) 

Its easy to work around it, but the extra parameter would be beneficial :)

**Comment by kaliiiiiiiiii** [comment]
Just use
- [`Pointer.click`](https://kaliiiiiiiiii.github.io/Selenium-Driverless/api/Input/#selenium_driverless.input.pointer.Pointer.click)
- [`Pointer.move_to`](https://kaliiiiiiiiii.github.io/Selenium-Driverless/api/Input/#selenium_driverless.input.pointer.Pointer.move_to)
- [`Pointer.double_click`](https://kaliiiiiiiiii.github.io/Selenium-Driverless/api/Input/#selenium_driverless.input.pointer.BasePointer.double_click)

Maybe `WebElemenet.double_click` and `WebElement.move_to` is worth a consideration?
