### ISSUE TITLE
[BUG] stuck on `about:blank` with chrome~=130

### ISSUE THREAD

**Issue by Skyceer** [kaliiiiiiiiii/Selenium-Driverless#272]
after chrome update Selenium-Driverless stopped working on version 130

Traceback 
```
    await self.driver.set_window_size(50, 100)
  File "C:\Users\slavaadminAppData\Local\Programs\Python\Python310\lib\site-packages\selenium_driverless\webdriver.py", line 1136, in set_window_size
    await self.set_window_rect(width=int(width), height=int(height))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium_driverless\webdriver.py", line 1217, in set_window_rect
    {"windowId": await self.current_window_id, "bounds": bounds})
  File "C:\Users\admin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium_driverless\webdriver.py", line 925, in current_window_id
    return result["windowId"]
TypeError: 'NoneType' object is not subscriptable
```

also does not open pages with error asyncio.exceptions.TimeoutError
on version < 130 everything works fine

**Comment by kaliiiiiiiiii** [comment]
@Skyceer please provide the script you used.

**Comment by kaliiiiiiiiii** [comment]
> The problem is not just with `set_window_size`, but with any interaction with the browser after startup. The readme code that is provided as an example does not work either
> 
> ```
> from selenium_driverless import webdriver
> from selenium_driverless.types.by import By
> import asyncio
> 
> 
> async def main():
>     options = webdriver.ChromeOptions()
>     async with webdriver.Chrome(options=options) as driver:
>         await driver.get('http://nowsecure.nl#relax', wait_load=True)
>         await driver.sleep(0.5)
>         await driver.wait_for_cdp("Page.domContentEventFired", timeout=15)
> 
>         # wait 10s for elem to exist
>         elem = await driver.find_element(By.XPATH, '/html/body/div[2]/div/main/p[2]/a', timeout=10)
>         await elem.click(move_to=True)
> 
>         alert = await driver.switch_to.alert
>         print(alert.text)
>         await alert.accept()
> 
>         print(await driver.title)
> 
> 
> asyncio.run(main())
> ```
> 
> Browser with about:blank link is launched, the script tries to open the link but gets an exception
> 
> `asyncio.exceptions.TimeoutError: page: "http://nowsecure.nl#relax" didn't load within timeout of 30`
> 
> The problem occurs on several machines after updating chrome to version 130

@Skyceer Can't reproduce that on the `dev` branch of driverless (does the dev branch work for you?) Also, what env are you on?

tested on Win10, `130.0.6723.59 (Offizieller Build) (64-Bit) (cohort: Stable Installs & Version Pins)`

**Comment by Skyceer** [comment]
Even the `dev` branch doesn't work for me

main machine: 
`Win 11 23H2`
chrome version: `130.0.6723.59 (Official Build) (64-bit) (cohort: Stable) `
Python version: `3.10.11`

second machine:
`Win 2022 21H2`
chrome version`130.0.6723.59 (Official Build) (64-bit) (cohort: Stable) `
Python Version: `3.11.9`

The problem is observed on two envs after upgrading chrome to version 130

**Comment by kaliiiiiiiiii** [comment]
> Changing to
> ```py
> if info.type == "page" and not > info.title.startswith("chrome-extension://"):
> ```
> from https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/722f11d25180a73ef1bd70a06ba611aa0d35c0fb/src/selenium_driverless/types/context.py#L108
> 
> ```
> {'targetId': '5FA2CCC5000335504CA5D730DE687E2C', 'type': 'page', 'title': '', 'url': 'chrome-extension://neajdppkdcdipfabeoofebfddakdcjhd/audio.html', 'attached': False, 'canAccessOpener': False, 'browserContextId': 'A4950040BC30D1949F4726F7993F4F80'}, {'targetId': '41F79EA0DAC1790699952CF9011B9413', 'type': 'background_page', 'title': 'Google Hangouts', 'url': 'chrome-extension://nkeimhogjdpnpccoofpliimaahmaaome/background.html', 'attached': False, 'canAccessOpener': False, 'browserContextId': 'A4950040BC30D1949F4726F7993F4F80'}
> ```

Might be the cause
Credits go to [discord message](https://discord.com/channels/1160554230881468440/1161414108646740101/1298014788709781574)

**Comment by lazidoca** [comment]
This bug still happens if `user_data_dir` is set (the first run may be OK, the second run will be stuck)
