### ISSUE TITLE
got no response for method: "Target.activateTarget"

### ISSUE THREAD

**Issue by ar-ctic** [kaliiiiiiiiii/Selenium-Driverless#277]
How do I set timeout and max_ws_size when creating a Target like this `target = await driver.new_window("tab")`?

**Comment by kaliiiiiiiiii** [comment]
1. `max_ws_size` is applied for all targets. In what usecase would you want to set it individually?
2. The timeout is hardcoded via https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ad8439437c08461688e5bf73eb050563343f15a9/src/selenium_driverless/types/context.py#L471 default at https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ad8439437c08461688e5bf73eb050563343f15a9/src/selenium_driverless/types/target.py#L1097-L1098 to 10s. Don't think this should ever be taking longer than 10s anyway? Maybe you've got blocking code in your project. You might consider using a thread (debug with `aiodebug`) or even better process per chrome instance .

Relevant source here:

https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/ad8439437c08461688e5bf73eb050563343f15a9/src/selenium_driverless/types/context.py#L445-L478

**Comment by kaliiiiiiiiii** [comment]
> I am trying to populate a chatroom and for that I have several instances of chrome open (as they´d all be logged in at the same account after a refresh if opened in the same chrome instance).
> 
> Currently I am doing several tasks with asyncio.gather
> 
> ```
> tasks = [handle_user(id_, username, password) for id_, username, password in users]
> await asyncio.gather(*tasks)
> ```
> 
> Each task then opens an Instance
> 
> ```
> handle_user(...):
>     user = User(id_, username, password, mailName)
>     
>     async with webdriver.Chrome(options=options, timeout = 180, max_ws_size=2**30) as driver:
>         await user.create_target(driver)
> ```
> 
> In User
> 
> ```
> async def create_target(self, driver: object) -> None:
>      self.target = await driver.new_window("tab")
> ```
> 
> When I´m having 10+ of these Instances some of them seem to crash and I´m getting a timeout error and I wonder how to fix it. Maybe this is a bad approach but its just a for fun project

Would assume this is either the limit of python, or Chrome.

=> use a python thread or process per chrome instance

**Comment by kaliiiiiiiiii** [comment]
Closing for now since this doesn't appear to be a bug//smth to fix or add at driverless

**Comment by ar-ctic** [comment]
processing helped a lot. Thanks
