### ISSUE TITLE
missing requests

### ISSUE THREAD

**Issue by Toxenskiy** [kaliiiiiiiiii/Selenium-Driverless#287]
After print(“F”) I press the button and the browser sends requests, but it does not see them, tried to press the button inside the network, tried before (through the code without hands) in any way does not catch it

but if I reload the page, it starts responding to requests.
```
print("F")
async with NetworkInterceptor(driver, on_response=callback_response, on_request=callback_response) as network:
    print("FZ_FF")
    async for request in network:
        print("FZ")
        print(request.request.url)
```

**Comment by Toxenskiy** [comment]
also another additional problem, after clicking on the button a window appears and driver can not find it, but if I reconnect to the browser, it immediately finds this window freyms do not change the frames

P.S. I tested it, if you put a delay before the window appears, everything is ok, but it's wrong, because I set timeout=18 when searching for items.

**Comment by ttlns** [comment]
Please always provide a https://stackoverflow.com/help/minimal-reproducible-example when opening an issue

Also, please do not report multiple different issues in one issue.
