### ISSUE TITLE
[BUG] does not collect Request after page load + does not always find the element, although it is loaded

### ISSUE THREAD

**Issue by Toxenskiy** [kaliiiiiiiiii/Selenium-Driverless#289]
Two problems:
1) It does not collect the request, after pressing the button, although it happens and in the network tab is displayed
2) The button is found once in a while, although it is always loaded after an error I check in the code of the element paths coincide.

Requests after button
![изображение](https://github.com/user-attachments/assets/063376c9-fb79-4110-84bb-00029d14daaf)

```
import asyncio
from selenium_driverless import webdriver
#from module_driver import browser_executable_path
from selenium_driverless.scripts.network_interceptor import NetworkInterceptor


async def main():
    opt = webdriver.ChromeOptions()
    #opt._binary_location = browser_executable_path

    driver = await webdriver.Chrome(options=opt)
    await driver.maximize_window()
    await driver.get("https://www.deepl.com/ru/translator", wait_load=True)
    async with NetworkInterceptor(driver) as network:
        button = await driver.find_element("xpath", "/html/body/div[1]/div[1]/div/div[3]/div[2]/div[2]/div[2]/div[1]/main/div[2]/nav/div/div[1]/div/div[1]/a[2]/div/div", timeout=10)
        await button.click()

        async for request in network:
            print(request)

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by ttlns** [comment]
You're running `async for request in network` after `await button.click()`. Therefore, this is to expect to miss some requests. 
Have you tried using the `on_response` callback? Can you confirm that to work as expected?

BTW: Thanks for the clean bug report this time!

**Comment by Toxenskiy** [comment]
Yes on response works, but it is inconvenient if I want to get query
results into a variable

Вс, 1 дек. 2024 г. в 04:11, kaliiiiiiiiiii ***@***.***>:

**Comment by ttlns** [comment]
> Yes on response works, but it is inconvenient if I want to get query results into a variable

Well how do you expect it to work otherwise haha?
You can try wrapping the `click` into `asyncio.ensure_future`
But in the end - there's always gonna be a little racing condition this way
That's just how async//programming works
