### ISSUE TITLE
How to exit NetworkInterceptor when no requests are intercepted?

### ISSUE THREAD

**Issue by theo-xx** [kaliiiiiiiiii/Selenium-Driverless#291]
Hi, I'm having a hard time to figure out how to exit NetworkInterceptor and continue with the script execution when no requests are intercepted.

I have a script that lands on a page with a "continue" button, I want to setup the interceptor, then click the button and check if some conditions occur with the background requests.
Here it is a working example (with the button navigating to a url)

html_page_with_button.html
```
<!DOCTYPE html>
<html>
<head>
	<title>Test interception</title>
</head>
<body>
	<button id="nextButton" onclick="window.location.href='https://httpbin.org/get'">Next</button>
</body>
</html>
```

interceptor_test.py
```
import traceback
import asyncio

from selenium_driverless.types.by import By
from selenium_driverless.webdriver import Chrome
from selenium_driverless.scripts.network_interceptor import NetworkInterceptor

async def interception_test():
    try:
        async with Chrome() as driver:
            await driver.get('html_page_with_button.html')
            elem = await driver.find_element(By.ID, 'nextButton')

            async with NetworkInterceptor(driver) as interceptor:
                print('start interceptor')
                asyncio.ensure_future(elem.click())

                async for data in interceptor:
                    print('enter for loop')
                    print(data.request.url)
                    if data.request.url == 'https://httpbin.org/get':
                        break

            print('script end')
            await driver.close()
            await driver.quit()
    except Exception:
        print(traceback.format_exc())

asyncio.run(interception_test())
```

The result (working as expected):
```
start interceptor
enter for loop
https://httpbin.org/get
script end
```

If for some reasons the button click doesn't fire requests in the background the script just gets stuck after entering the interceptor.
Here I simulate the button click doing nothing by removing the js redirect:
```
<!DOCTYPE html>
<html>
<head>
	<title>Test interception</title>
</head>
<body>
	<button id="nextButton" onclick="">Next</button>
</body>
</html>
```
Result:
```
start interceptor
```

Maybe I'm missing something obvious, I'm not an expert at all.
Thank you

**Comment by ttlns** [comment]
`async for data in interceptor` yields infinitely until you use the `break` statement.
`data.request.url == 'https://httpbin.org/get'` is just probably never true for your webpage => adapt the condition

Hope this answers your question?

**Comment by theo-xx** [comment]
> `async for data in interceptor` yields infinitely until you use the `break` statement. `data.request.url == 'https://httpbin.org/get'` is just probably never true for your webpage => adapt the condition

No, the condition is correct. It works as intended when requests are fired in background, the condition is fullfilled, it breaks and exit.
My question is how do I break when no requests are intercepted? Sometimes there are no requests fired after the button click so the condition is not met in those cases and the script hangs infinitely

**Comment by ttlns** [comment]
> > `async for data in interceptor` yields infinitely until you use the `break` statement. `data.request.url == 'https://httpbin.org/get'` is just probably never true for your webpage => adapt the condition
> 
> No, the condition is correct. It works as intended when requests are fired in background, the condition is fullfilled, it breaks and exit. My question is how do I break when no requests are intercepted? Sometimes there are no requests fired after the button click so the condition is not met in those cases and the script hangs infinitely

iterate on it inside an external function & run with `asyncio.wait_for`
Also, you might want to rethink how the script is supposed to know whether there are gonna be any further requests.
