### ISSUE TITLE
[Feature request] add request history to network_interceptor

### ISSUE THREAD

**Issue by Toxenskiy** [kaliiiiiiiiii/Selenium-Driverless#292]
Why this feature is needed:
We need it to parsing requests for certain actions without creating crutches and global variables

We open the Interceptor together with the history request
execute our code and then just get the request history and analyze what happened during the execution of this or that code.

You can also make an empty query at the beginning of the aiter to trigger certain actions
Which is a good, but not very nice solution
```
PARAM: request_history: bool = False

self.request_history = [] if request_history else request_history
self.request_changed_history = [] if request_history else request_history

in _paused_handler:

if isinstance(self.request_history, list):
    self.request_history.append(request)

```

**Comment by ttlns** [comment]
> We need it to parsing requests for certain actions without creating crutches and global variables

Don't think implementing this is would require global variables?
in python, lists are passed by reference anyway afaik - could just pass the `history=[]` to the `on_request` handler with a lambda.

Issue I see with your suggestion:
Using this is really bad regarding performance & memory management. Further, the body for a response can't be requested from the browser after to much time has passed afaik (probably memory limited cache in chrome)

Therefore, don't think that's smth which should be used, except for testing.

**Comment by Toxenskiy** [comment]
Global variables are really not necessary, at the moment I use this code for my needs.

In order to write to the history, of course, we will have to get body and other data at once

The memory problem is quite relative, because it depends on who is writing the code.
Also using NetworkInterceptor means using it on small pieces of code. Because its design is rather inconvenient for use on large pieces of code.

![изображение](https://github.com/user-attachments/assets/3c165d82-9452-48c7-860e-c077446ae140)

**Comment by ttlns** [comment]
> The memory problem is quite relative, because it depends on who is writing the code.

> Also using NetworkInterceptor means using it on small pieces of code. Because its design is rather inconvenient for use on large pieces of code

Wdym?

**Comment by Toxenskiy** [comment]
I mean, there should be no memory issues (not cache in the browser) unless all the code is wrapped in NetworkInterceptor.

**Comment by ttlns** [comment]
> I mean, there should be no memory issues (not cache in the browser) unless all the code is wrapped in NetworkInterceptor.

Maybe you're using google translate? This doesn't make much sense to me logically.
Either way - just storing all request history will cause a memory leak & pile up. Therefore, I won't implement this.
