### ISSUE TITLE
support proxy with auth

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [kaliiiiiiiiii/Selenium-Driverless#30]
thanks for u efforts but i want example for support proxy with auth 
thanks sir

**Comment by kaliiiiiiiiii** [comment]
use https://github.com/kaliiiiiiiiii/Selenium-Profiles#set-proxies-dynamically-or-with-options and https://github.com/kaliiiiiiiiii/Selenium-Profiles#selenium-driverless

**Comment by mostafakamelomarrslan** [comment]
sir it's diffrent libs !
