### ISSUE TITLE
is there a way to start it with firefox ?

### ISSUE THREAD

**Issue by firaki12345-cmd** [kaliiiiiiiiii/Selenium-Driverless#300]
SO my mian browser is firefox, but for selenium_driverless i use chrome.

so is there a way to use firefox instead ? thanks

**Comment by ttlns** [comment]
Simply: No.
Firefox is going to deprecate CDP (https://fxdx.dev/deprecating-cdp-support-in-firefox-embracing-the-future-with-webdriver-bidi/) and would have to re-implement everything specifically for firefox. I'm sure there are plenty other libraries for FF around tho:)
