### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by mostafakamelomarrslan** [kaliiiiiiiiii/Selenium-Driverless#31]
i am sorry for say that but i am noob in python 
import json
import requests
from selenium_profiles.webdriver import Chrome
from selenium_profiles.profiles import profiles
from selenium_driverless.webdriver import ChromeOptions
from selenium_driverless.types.by import By

profile = profiles.Windows()  # or .Android
profile["proxy"] = {
  "proxy":""
  }
options = ChromeOptions()

driver = Chrome(profile, options=options, driverless_options=True)
that's my code how i can support proxy please

**Comment by kaliiiiiiiiii** [comment]
I allready answered your question in #30 The code you provided yhould be working fine. alternatively, you could also use https://github.com/kaliiiiiiiiii/Selenium-Injector
Please don't open any new issues except if there's a bug.
