### ISSUE TITLE
detected with RDP

### ISSUE THREAD

**Issue by DeltaDarkness** [kaliiiiiiiiii/Selenium-Driverless#35]
when i used selenium in my device was undetected when i used in RDP detected but when click on checkbox it's pass there is any code make checkbox when fail to do it auto
and thanks for u efforts

**Comment by kaliiiiiiiiii** [comment]
@DeltaDarkness 
please clarify yours issue
- write full sentences
- use interpunktion

**Comment by DeltaDarkness** [comment]
`from selenium_driverless import webdriver
from selenium_driverless.types.by import By
import time
import asyncio


async def main():
    options = webdriver.ChromeOptions()
    async with webdriver.Chrome(options=options) as driver:
        await driver.get('http://nowsecure.nl#relax')
        await time.sleep(10)
        await driver.wait_for_cdp(event="Page.loadEventFired", timeout=10)
        await asyncio.sleep(0.5)
        login_button = await driver.find_element(By.XPATH, value='//*[@id="challenge-stage"]/div/label/input')
        await login_button.click()



asyncio.run(main())
`
that's my code
![Capture](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/142715068/b00f3c12-6e10-4e12-b3bf-96da692427f2)

**Comment by kaliiiiiiiiii** [comment]
well I suppose they've blocked windows servers:)
Or you can try using https://github.com/kaliiiiiiiiii/Selenium-Profiles

closing as this library doesn't aim to emulate devices
