### ISSUE TITLE
how i can pass the captcha 

### ISSUE THREAD

**Issue by DeltaDarkness** [kaliiiiiiiiii/Selenium-Driverless#36]
![369328805_978412966729775_754531320192387286_n](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/142715068/997312bc-d47a-4b0f-a876-ea394a748284)

**Comment by kaliiiiiiiiii** [comment]
@DeltaDarkness undless there's a bug, please only open a [discussion](https://github.com/kaliiiiiiiiii/Selenium-Driverless/discussions).
closing therefore
