### ISSUE TITLE
[Future request] support `options.add_extension()`

### ISSUE THREAD

**Issue by DeltaDarkness** [kaliiiiiiiiii/Selenium-Driverless#37]
![Capture](https://github.com/kaliiiiiiiiii/Selenium-Driverless/assets/142715068/0152cfe1-8afe-4dd3-8af4-0addc8410c6e)

**Comment by kaliiiiiiiiii** [comment]
@DeltaDarkness The error tells you that it isn't implemented.

You can use 
```python
options.add_argument('--load-extension={}'.format(unpacked_extension_path))
``` 
as a workaround

**Comment by kaliiiiiiiiii** [comment]
moving to https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/8, closing therefore
