### ISSUE TITLE
'Chrome' object has no attribute 'pointer'

### ISSUE THREAD

**Issue by smartsimba** [kaliiiiiiiiii/Selenium-Driverless#60]
Chrome version: 117.0.5938.92 (Official Build) (64-bit)
Executive function: await driver.pointer.click()
Error: 'Chrome' object has no attribute 'pointer'
Thank you~~

**Comment by kaliiiiiiiiii** [comment]
@smartsimba please provide the full script you tried

**Comment by kaliiiiiiiiii** [comment]
@smartsimba just look at the documentation, it should be `driver.current_pointer` 
https://github.com/kaliiiiiiiiii/Selenium-Driverless#pointer-interaction
