### ISSUE TITLE
Error while switching to captcha iframe

### ISSUE THREAD

**Issue by ruslanx3m** [kaliiiiiiiiii/Selenium-Driverless#7]
`You might use driver.switch_to.target(driver.targets[0].target_id)`
Error while switching to captcha iframe

```python
    try:
        # Wait for captcha iframe
        wait = WebDriverWait(driver, 10)
        captcha_iframe = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "iframe[title='Widget containing a Cloudflare security challenge']")))
        time.sleep(1)
        driver.switch_to.frame(captcha_iframe)

    except Exception as e:
        print(e)
        print("Error while switching to captcha iframe")
        return False
```

tried many solution but cant switch to iframe

**Comment by kaliiiiiiiiii** [comment]
Your code would require the following implementations:
- `WebDriverWait`
- `EC` (expected-conditions)
- `driver.switch_to.frame`

Workaround for now:
1. search your `iframe` in `driver.targets` (for example by the url)
2. get the target's `target_id` (included in `driver.targets`)
3. switch to the `iframe` based on the `target_id` with `driver.switch_to.target(target_id)`

**Comment by kaliiiiiiiiii** [comment]
Added to [TODO](https://github.com/kaliiiiiiiiii/Selenium-Driverless/blob/dev/README.md#todo)

**Comment by ruslanx3m** [comment]
Switching to iframe 62F39492BC29F01259DA297E862DA9DA
**'str' object has no attribute 'to_json'**
Error while switching to iframe

    **targets = driver.targets

    print("Targets:", targets)

    target = None

    iframe_url_pattern = re.compile(r"turnstile")

    for target in targets:
        if target["type"] == "iframe":
            if iframe_url_pattern.search(target["url"]):
                target = target
                print(target["url"])
                break

    if not target:
        print("No iframe found")
        return False
    
    print("Switching to iframe", target["targetId"])

    try:
        driver.switch_to.target(target["targetId"])
    except Exception as e:
        print(e)
        print("Error while switching to iframe")
        return False

    print("Switched to iframe")**

**Comment by kaliiiiiiiiii** [comment]
> Switching to iframe 62F39492BC29F01259DA297E862DA9DA **'str' object has no attribute 'to_json'** Error while switching to iframe
> 
> ```
>     targets = driver.targets
> 
>     print("Targets:", targets)
> 
>     target = None
> 
>     iframe_url_pattern = re.compile(r"turnstile")
> 
>     for target in targets:
>         if target["type"] == "iframe":
>             if iframe_url_pattern.search(target["url"]):
>                 target = target
>                 print(target["url"])
>                 break
> 
>     if not target:
>         print("No iframe found")
>         return False
>     
>     print("Switching to iframe", target["targetId"])
> 
>     try:
>         driver.switch_to.target(target["targetId"])
>     except Exception as e:
>         print(e)
>         print("Error while switching to iframe")
>         return False
> 
>     print("Switched to iframe")
> ```

@ruslanx3m actually, that might be a bug
I'll re-open for now and investigate
