### ISSUE TITLE
cdp_socket.exceptions.CDPError: {'code': -32000, 'message': 'Could not find node with given id'}

### ISSUE THREAD

**Issue by samyeid** [kaliiiiiiiiii/Selenium-Driverless#85]
> ```python
> from selenium_driverless import webdriver
> from selenium_driverless.types.by import By
> import asyncio
> async def main():
>     options = webdriver.ChromeOptions()
>     async with webdriver.Chrome(options=options) as driver:
>         await driver.get('https://www.google.com/', wait_load=True)
>         elements =   await driver.find_element(By.CSS_SELECTOR,'#APjFqb')
>         print(elements)
>         await elements.write('forex')
>         elements1 = await driver.find_element(By.CSS_SELECTOR, 'body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.FPdoLc.lJ9FBc > center > input.gNO89b',timeout=300)
>         await elements1.click()
>         elements2 = await driver.find_element(By.CSS_SELECTOR, '#rso > div:nth-child(2) > div > div > div > div > div > div > div > div.yuRUbf > div > span > a > h3',timeout=300)
>         #await elements2.click()
>         input('a: ')
> 
> asyncio.run(main())
> ```

> ```
> C:\Users\PycharmProjects\new\venv\Scripts\python.exe C:/Users/samm/PycharmProjects/untitled/mm.py
> WebElement("None", obj_id=None, node_id="59", backend_node_id=None, context_id=None)
> Traceback (most recent call last):
>   File "C:\Users\PycharmProjects\untitled\mm.py", line 17, in <module>
>     asyncio.run(main())
>   File "C:\Users\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "C:\Users\PycharmProjects\untitled\mm.py", line 13, in main
>     elements2 = await driver.find_element(By.CSS_SELECTOR, '#rso > div:nth-child(2) > div > div > div > div > div > div > div > div.yuRUbf > div > span > a > h3',timeout=300)
>   File "C:\Users\PycharmProjects\new\venv\lib\site-packages\selenium_driverless\webdriver.py", line 662, in find_element
>     return await target.find_element(by=by, value=value, parent=parent, timeout=timeout)
>   File "C:\Users\PycharmProjects\new\venv\lib\site-packages\selenium_driverless\types\target.py", line 547, in find_element
>     return await parent.find_element(by=by, value=value, timeout=timeout)
>   File "C:\Users\PycharmProjects\new\venv\lib\site-packages\selenium_driverless\types\webelement.py", line 245, in find_element
>     elems = await self.find_elements(by=by, value=value)
>   File "C:\Users\PycharmProjects\new\venv\lib\site-packages\selenium_driverless\types\webelement.py", line 280, in find_elements
>     res = await self.__target__.execute_cdp_cmd("DOM.querySelectorAll", {"nodeId": node_id,
>   File "C:\Users\PycharmProjects\new\venv\lib\site-packages\selenium_driverless\types\target.py", line 742, in execute_cdp_cmd
>     result = await self.socket.exec(method=cmd, params=cmd_args, timeout=timeout)
>   File "C:\Users\PycharmProjects\new\venv\lib\site-packages\cdp_socket\socket.py", line 69, in exec
>     return await asyncio.wait_for(self._responses[_id], timeout=timeout)
>   File "C:\Users\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 481, in wait_for
>     return fut.result()
> cdp_socket.exceptions.CDPError: {'code': -32000, 'message': 'Could not find node with given id'}
> ```

how can i fix this error :  `cdp_socket.exceptions.CDPError: {'code': -32000, 'message': 'Could not find node with given id'}`please

**Comment by kaliiiiiiiiii** [comment]
dublicate to https://github.com/kaliiiiiiiiii/Selenium-Driverless/issues/70
please make sure you have `selenium-driveress==1.6.2` installed

**Comment by samyeid** [comment]
> dublicate to #70 please make sure you have `selenium-driveress==1.6.2` installed

i already installed selenium-driveress==1.6.2` but i show this error how to fix it please?

**Comment by kaliiiiiiiiii** [comment]
> > dublicate to #70 please make sure you have `selenium-driveress==1.6.2` installed
> 
> i already installed selenium-driveress==1.6.2` but i show this error how to fix it please?

well then I unfortanely don't know either haha:) Maybe try with a newer version of chrome or//and windows

**Comment by henzycuong1** [comment]
got the same
```
Traceback (most recent call last):

    if len(driver.find_elements(By.XPATH,'//a[descendant::*[text()="Venom Chrome Extension"]]')) > 0:
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\sync\webdriver.py", line 38, in syncified
    return self._loop.run_until_complete(res(*args, **kwargs))
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\webdriver.py", line 675, in find_elements
    return await target.find_elements(by=by, value=value, parent=parent)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\types\target.py", line 552, in find_elements
    return await parent.find_elements(by=by, value=value)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\types\webelement.py", line 305, in find_elements
    return await self.execute_script(scipt, value, serialization="deep", timeout=10, unique_context=True)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\types\webelement.py", line 757, in execute_script
    return await self.__exec__(script, *args, max_depth=max_depth, serialization=serialization,
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\types\deserialize.py", line 183, in __exec__
    base_obj_id = await self.__obj_id_for_context__(exec_context)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\types\webelement.py", line 147, in __obj_id_for_context__
    res = await self.__target__.execute_cdp_cmd("DOM.resolveNode", args)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium_driverless\types\target.py", line 742, in execute_cdp_cmd
    result = await self.socket.exec(method=cmd, params=cmd_args, timeout=timeout)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\site-packages\cdp_socket\socket.py", line 69, in exec
    return await asyncio.wait_for(self._responses[_id], timeout=timeout)
  File "C:\Users\Four\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
cdp_socket.exceptions.CDPError: {'code': -32000, 'message': 'No node with given id found'}
```
