### ISSUE TITLE
[BUG] click on selectors fails

### ISSUE THREAD

**Issue by miltonvo** [kaliiiiiiiiii/Selenium-Driverless#94]
Hi for all

im trying to find this input field:
```python
input_element = await self.driver.find_element(By.CSS_SELECTOR, ".bsf-StakeBox_StakeValue.bsf-StakeBox_StakeValue-input.bsf-StakeBox_StakeValue-empty")
```

and then write some value
```python
await input_element.write(str(self.user_config.goal_value))
```

i see the script writing on field the value but if i click on another place the value disappears

thanks for if someone can helps to solve this

**Comment by kaliiiiiiiiii** [comment]
Thanks for submitting this issue.
I'm working on a cross-platform patch for this. 
Still will take some time tho:)

**Comment by Bonfahh** [comment]
@miltonvo can you explain more about your solution ?

**Comment by Bonfahh** [comment]
I'm having the same problem here

**Comment by kaliiiiiiiiii** [comment]
> example
> 
> ```python
> driver.execute_script("document.getElementById('FIND ELEMENT').value = arguments[0]", Your Argument)
> ```

you can pass WebElements as an argument directly as well. Any js like that will be detectable tho.

**Comment by Bonfahh** [comment]
Yeah, it doesn't work, changing the value or innerhtml even though the appearing text change it doesn't update the button that is disabled without a value

**Comment by tankow79** [comment]
Hi friends, this is what worked for me

```
dropdown_element = driver.find_element(By.XPATH, "FIND ELEMENT")  # find the dropdown
dropdown_element.click()  # click the dropdown
driver.execute_script(f"arguments[0].value = '{random.randint(1, 12)}';", dropdown_element)  # I choose a random element
driver.execute_script("arguments[0].dispatchEvent(new Event('change', { bubbles: true }));", dropdown_element) # I confirm the selection of the item
```

**Comment by kaliiiiiiiiii** [comment]
> Hi friends, this is what worked for me
> 
> ```
> dropdown_element = driver.find_element(By.XPATH, "FIND ELEMENT")  # find the dropdown
> dropdown_element.click()  # click the dropdown
> driver.execute_script(f"arguments[0].value = '{random.randint(1, 12)}';", dropdown_element)  # I choose a random element
> driver.execute_script("arguments[0].dispatchEvent(new Event('change', { bubbles: true }));", dropdown_element) # I confirm the selection of the item
> ```

Yeah "works" sure. But detectable as well.

**Comment by thekrakatoa** [comment]
> Excelent, thanks
> 
> solved with simulating sending keys and write value with javascript :)

Could you share the solution? I'm interested as well :)

**Comment by kaliiiiiiiiii** [comment]
resolved with https://github.com/kaliiiiiiiiii/Selenium-Driverless/pull/273
