### ISSUE TITLE
fix error 1009 for websockets (message to big)

### ISSUE THREAD

**Issue by AdonisCodes** [kaliiiiiiiiii/Selenium-Driverless#96]
Solution, go through litterly every single line that has the value max_value=max_value & then increase it to like 20000000. Please create a better fix, All I know is that I increased the max bytes or something that the ws can send. So the main contributor, can you please increase the size because Sometimes it gets that error ( After I did this hack it just works now )

**Comment by kaliiiiiiiiii** [comment]
@AdonisCodes 
Can you provide a example script? I haven't encountered this error yet anywhere.

**Comment by kaliiiiiiiiii** [comment]
will be fixed with https://github.com/kaliiiiiiiiii/Selenium-Driverless/pull/100

**Comment by AdonisCodes** [comment]
Thanks. Sorry forgot to send.

**Comment by kaliiiiiiiiii** [comment]
fixed with https://github.com/kaliiiiiiiiii/Selenium-Driverless/pull/100
